### ISSUE TITLE
Reorg Handling is Broken

### ISSUE THREAD

**Issue by wtogami** [bitpay/insight-api#103]
180dc1341da48ee9e9215378baccf8d11d9575a0

* Double spent transactions from the orphaned block cannot be queried.
* Earlier versions of Insight would successfully serve double spent transactions, although they had confirmations: 0 instead of -1 as bitcoind gettransaction would do.  -1 is correct.
* The orphaned block is considered to be in the Main chain.
```
    //TODO can we get this from RPC .height?
    self.getHeight(hash, function(err, height) {
      if (err) return cb(err);

      info.isMainChain = height ? true : false;
```

**Comment by posita** [comment]
> We definitely want to support double spends reports and regtest mode. I will work on that for the next insight-api version (v0.3), following your comments.

What about #305?

**Comment by braydonf** [comment]
@wtogami @posita regtest support is currently supported. 

Also orphaned transactions should still be able to be queried from bitcoind, as the txindex will include these as well, and orphaned blocks are not considered as part of the main chain.
