### ISSUE TITLE
Bad genesis block. Network mismatch between Insight and bitcoind?

### ISSUE THREAD

**Issue by ghost** [bitpay/insight-api#115]
I a few questions I have regarding getting insight to work with an altcoin.   I am able to connect to my RPC however I am receiving the following error: Bad genesis block. Network mismatch between Insight and bitcoind? Insight is configured for:livenet

I have investigated network.js and see I should modify the following details in order to use insight with an alt-coin:
- magic 
- addressVersion (base58.cpp)
- privKeyVersion  (base58.cpp)
- hkeyPublicVersion 
- hkeyPrivateVersion
- genesis hash (main.cpp)
- genesis merkle_root (main.cpp)
- nonce (main.cpp)
- timestamp (main.cpp)
- bits (main.cpp)

Note: Does bundle.js need to be updated as well?

Command used to start Insight: 

```
INSIGHT_NETWORK=livenet BITCOIND_HOST="127.0.0.1"  BITCOIND_USER=miner1 BITCOIND_PASS=passwordinputhere INSIGHT_PUBLIC_PATH=public BITCOIND_P2P_PORT=7143  npm start
```

Current config of network.js

```
exports.livenet = {
  name: 'livenet',
  magic: hex('f9beb4d9'),
  addressVersion: 0x1C,
  privKeyVersion: 0X9C,
  P2SHVersion: 5,
  hkeyPublicVersion: 0x0488b21e,
  hkeyPrivateVersion: 0x0488ade4,
  genesisBlock: {
    hash: hex('F1B4CDF03C86099A0758F1C018D1A10BF05AFAB436C92B93B42BB88970DE9821'),
    merkle_root: hex('04C3AE72B7E099C2A3FE2862AB6280B09C8B1E4CD217237EBB2D0CACC20AAA68'),
    height: 0,
    nonce: 1120954,
    version: 1,
    prev_hash: buffertools.fill(new Buffer(32), 0),
    timestamp: 1382342087,
    bits: 504365055,
  },
```

Cannacoin Genesis Block Details:

```
{
    "hash" : "f1b4cdf03c86099a0758f1c018d1a10bf05afab436c92b93b42bb88970de9821",
    "confirmations" : 97791,
    "size" : 297,
    "height" : 0,
    "version" : 1,
    "merkleroot" : "04c3ae72b7e099c2a3fe2862ab6280b09c8b1e4cd217237ebb2d0cacc20aaa68",
    "tx" : [
        "04c3ae72b7e099c2a3fe2862ab6280b09c8b1e4cd217237ebb2d0cacc20aaa68"
    ],
    "time" : 1382342087,
    "nonce" : 1120954,
    "bits" : "1e0fffff",
    "difficulty" : 0.00024414,
    "nextblockhash" : "02e06d163d6be86cb1c154411df0358bc6f6198d36aa3f0af3f173e6c07e50c6"
}
```

Is there something I am missing in order to correctly verify and read the genesis block?

**Comment by doged** [comment]
how did you come to the hkeypublic & hkeyprivate? @matiu any idea?

**Comment by doged** [comment]
nevermind guys, got it working. i had only reversed the hash, not actually flipped it in groups of two's.. sheesh lol

**Comment by doged** [comment]
well, i have it *mostly* working. still disconnecting from 8333, although i can telnet to it, so it is open.

in debug im having a messagestart error, so im thinking that its the magic hex?

how can i obtain the magic hex from my main cpp? i only found 4 sets of 4 what appear to be hex codes, i tried that but to no avail..

**Comment by doged** [comment]
unsigned char pchMessageStart[4] = { 0xf7, 0xa7, 0x7e, 0xff };

why does this not look accurate for my magic number?

**Comment by doged** [comment]
got it but i cant get the p2p port to connect. rpc syncs up though.
