### ISSUE TITLE
Inconsistent UTXO output

### ISSUE THREAD

**Issue by ghost** [bitpay/insight-api#129]
Taking `/addr/:address/utxo` fails to return a field for 0 confirmation UTXO. This is a little untidy. The field `confirmations` should always appear and reflect the number of confirmations, and `0` for none. Depending on programming language we now need to test for the existence of the `confirmations` field instead of just reading the value.

Example data.

```
  {
    "address": "13VGRb2nP8VazMpphRGSx5oJcWTWTZjvyd",
    "txid": "7ec78c67448430743c891f6d01915964f3aec5e7c0f8975e6c465efe85bc2be1",
    "vout": 2,
    "ts": 1402959912,
    "scriptPubKey": "76a9141b48c61315a9e4b8da02084e609f1f87e53cd66588ac",
    "amount": 0.05914,
    "confirmationsFromCache": false
  },
  {
    "address": "13VGRb2nP8VazMpphRGSx5oJcWTWTZjvyd",
    "txid": "3922f532766e5654e02b3f8a7d3c3a5a912be25f661c754fe82d4456f99222fe",
    "vout": 0,
    "ts": 1402934941,
    "scriptPubKey": "76a9141b48c61315a9e4b8da02084e609f1f87e53cd66588ac",
    "amount": 0.0001086,
    "confirmations": 56,
    "confirmationsFromCache": false
  },
```

**Comment by posita** [comment]
It looks like the `confirmations` field is going away. See: https://github.com/bitpay/insight-api#notes-on-upgrading-from-v02

**Comment by braydonf** [comment]
It's still there, confirmations is set to zero when it's unconfirmed.
