### ISSUE TITLE
Stale cache

### ISSUE THREAD

**Issue by LTGIV** [bitpay/insight-api#130]
When watching an address with a pre-existing amount for an additional amount that's coming in, it will stay marked as unconfirmed and not show up as total received.  I'd assume that it would wait for 6 confirmations before totaling it out instead of continuing to show it as unconfirmed, and at nearly 50 confirmations (which does update on Insight) it still is marked as unconfirmed.  I tried appending ?noCache=1 to the end of it, and still, the only information that updates is the number of confirmations which matches the information on blockchain.info.

**Comment by braydonf** [comment]
Outdated
