### ISSUE TITLE
Socket.IO doesn't work

### ISSUE THREAD

**Issue by nateless** [bitpay/insight-api#133]
Getting 
```
WebSocket connection to 'ws://localhost/socket.io/1' failed: Connection closed before receiving a handshake response
```
when trying to connect to it. No logs in the console.

**Comment by prabjot678** [comment]
Get the  same issue.

**Comment by doged** [comment]
anyone have a solution to this? just took me forever to configure this, and now im realized the websocket end doesnt work, and i dont see a way to troubleshoot it.

**Comment by braydonf** [comment]
See: https://github.com/bitpay/insight-api/issues/330#issuecomment-224659724
