### ISSUE TITLE
Balance and tx difference between blockchain and insight for an address

### ISSUE THREAD

**Issue by robby-dermody** [bitpay/insight-api#134]
https://blockchain.info/address/13VGRb2nP8VazMpphRGSx5oJcWTWTZjvyd
http://live.insight.is/api/addr/13VGRb2nP8VazMpphRGSx5oJcWTWTZjvyd

Both are on bitcoin block 309637 at the moment

Insight reports balance as 0.77074022 (no unconfirmed balance)
Blockchain reports balance as 0.86958301 BTC

(we see the same issue on our locally running version of insight as well)

More info: https://github.com/CounterpartyXCP/counterpartyd/issues/161

Any idea what's up?

**Comment by braydonf** [comment]
The first listed addresses are showing the same balance currently, and the balance doesn't include the unconfirmed amount.

Regarding the received balance, I think it has to do with the change address, as posted here: https://github.com/bitpay/insight-api/issues/351
