### ISSUE TITLE
API and Web-Gui have different information at same time 

### ISSUE THREAD

**Issue by ghost** [bitpay/insight-api#135]
https://www.dropbox.com/s/pisj9mo5rw03cbv/2014-07-08-174514_1356x825_scrot.png
https://www.dropbox.com/s/ow3mmrwbtzmh9y9/2014-07-08-174424_1274x813_scrot.png

**Comment by braydonf** [comment]
Utxos are no longer showing up for comparison with latest version. Let us know if you see any inconsistencies.
