### ISSUE TITLE
Insight doesn't work properly if it starts when bitcoind not fully initialized

### ISSUE THREAD

**Issue by robby-dermody** [bitpay/insight-api#137]
If insight is started up before bitcoind has had a chance to fully start up, it will complain about not being able to access bitcoind. It will then, however, continue to run, however API accesses to it will not work.

Can we make insight retry a certain amount of times, or do something so that this situation does not happen? From the standpoint of the logs, if you don't catch this issue, you'll sit there wondering why things can't access insight, while in the logs it appears to "work" fine (e.g. downloading txs, not reporting errors, etc)

**Comment by braydonf** [comment]
No longer relevant with the latest version as bitcoind runs in the same process now.
