### ISSUE TITLE
After a few days the Insight-API stops syncing 100%

### ISSUE THREAD

**Issue by Bushstar** [bitpay/insight-api#148]
I can start the Insight-API and watch it fully synchronise with the rest of the network. However after a few days of running the Insight-API stops fully syncing. I just logged on to the server and found it at 95%, I am not sure whether it is still synchronising when it shows less than 100%.

I am hoping that someone can give some guidance or a tip or two on debugging this problem. If you have any ideas or experience of this then please share.

The Insight-API is running on Ubuntu Server 13.10 64-bit.

**Comment by 9cat** [comment]
still have this issue in v0.2.12

and trigger that can't make copay update information properly.

**Comment by braydonf** [comment]
No longer relevant with v0.3.0
