### ISSUE TITLE
Unconfirmed transactions that never disappear

### ISSUE THREAD

**Issue by btcdrak** [bitpay/insight-api#149]
We are seeing this strange issue from time to time. We're using `insight` for an altcoin, but this issue has happened several times on a bitcoin installation. The issues are definitely not because of changes we made since we just adapted the network settings for Viacoin, nothing else substantial.

I will copy the data here just in case we have to reset the databases:

http://explorer.viacoin.org/api/addr/VoXwXixfzPSe1Ysiwg7tS8DpCDMiSfk8VV you can see `"unconfirmedBalanceSat":0` (we just used sync.js -D to reload so this worked)
```json
{"addrStr":"VoXwXixfzPSe1Ysiwg7tS8DpCDMiSfk8VV","balance":22.96536,"balanceSat":2296536000,"totalReceived":302.82292,"totalReceivedSat":30282292000,"totalSent":279.85756,"totalSentSat":27985756000,"unconfirmedBalance":0,"unconfirmedBalanceSat":0,"unconfirmedTxApperances":0,"txApperances":11,"transactions":["a6524ba026f884b743a5d27d085a2b595c15a95f75dae69c2460b6c932e7c591","d283a6355241d97d1644796e3fa330fbcd261f4097068969a309d4bd9d99579b","1bbfb20145f016ae2c618b02f764a78b19a5bdb731bc7f7cddf67714254a3147","391d730ed4ed83981cd235bf40c5bd9d5d50eed767b9b525496bcedac1990677","5797e6dd6c08fbab011acd6a67d650653de2d5ffb76ad8747bc325d09b261f55","58156857245b0b2d59333ecbbbfd618e80d96793e83a4d07e4829d8d415f7f1f","ae51904e30dcba60051636fd93f8ef7236a207633c40e4517b058588bac0c840","abdd7e15ed9599075d919f64be64d26eb923f3764257ea657455ab2e6abaf472","97e3bdcc19222362a9dd2513bda739230e0ca2d7b8b9b01632e25860292c1d0d","90c6d855f3cd4c80db3454a783e4ea7e25bb30a3898659b5cc486ea77ad97bac","b9e12206c135f098ca676480494dade8daeaab58f50e9cd32b8477448992ac87"]}
```

http://clearwallet.co:3000/api/addr/VoXwXixfzPSe1Ysiwg7tS8DpCDMiSfk8VV you can see `"unconfirmedBalanceSat":-436000`
```json
{"addrStr":"VoXwXixfzPSe1Ysiwg7tS8DpCDMiSfk8VV","balance":45.93944,"balanceSat":4593944000,"totalReceived":279.8532,"totalReceivedSat":27985320000,"totalSent":233.91376,"totalSentSat":23391376000,"unconfirmedBalance":-0.00436,"unconfirmedBalanceSat":-436000,"unconfirmedTxApperances":1,"txApperances":10,"transactions":["a6524ba026f884b743a5d27d085a2b595c15a95f75dae69c2460b6c932e7c591","d283a6355241d97d1644796e3fa330fbcd261f4097068969a309d4bd9d99579b","1bbfb20145f016ae2c618b02f764a78b19a5bdb731bc7f7cddf67714254a3147","391d730ed4ed83981cd235bf40c5bd9d5d50eed767b9b525496bcedac1990677","5797e6dd6c08fbab011acd6a67d650653de2d5ffb76ad8747bc325d09b261f55","58156857245b0b2d59333ecbbbfd618e80d96793e83a4d07e4829d8d415f7f1f","ae51904e30dcba60051636fd93f8ef7236a207633c40e4517b058588bac0c840","abdd7e15ed9599075d919f64be64d26eb923f3764257ea657455ab2e6abaf472","97e3bdcc19222362a9dd2513bda739230e0ca2d7b8b9b01632e25860292c1d0d","90c6d855f3cd4c80db3454a783e4ea7e25bb30a3898659b5cc486ea77ad97bac","b9e12206c135f098ca676480494dade8daeaab58f50e9cd32b8477448992ac87"]}
```

Another interesting detail is if you try to look at an address that has such a problem (where insight thinks there is an unconfirmed tx pending, but there isnt) then no transaction data loads.

Oo what isnt clear is whether it's a transaction that never confirmed, or it confirmed. Cant tell because it also breaks display on insight. 

One theory is Insight sees the txid as unconfirmed, probably goes looking for it to extract the data and cant find it...?

**Comment by deweller** [comment]
This happened for me during the recent spam attacks to the bitcoin network.

I have a local application that composed and sent a valid transaction to the local bitcoind server.  This transaction sat in the mempool of bitcoind, but was not accepted by its peers and was eventually dropped by bitcoind.

When this happened Insight did not purge this transaction from its own database.

**Comment by braydonf** [comment]
Outdated. This should also no longer be an issue as unconfirmed transactions are from the bitcoind mempool. Also the txids listed in an address summary will include confirmed txs.
