### ISSUE TITLE
Changing filter for front page block listing to show blocks older than...

### ISSUE THREAD

**Issue by ghost** [bitpay/insight-api#157]
Great program, got it running here: http://explorer.neoscoin.com but having some issues with it displaying blocks on the main page. Blocks work fine on dated pages, but I'd like to change the filter for the front page listing to show the last set of blocks regardless of date/time.

**Comment by braydonf** [comment]
This may be a change necessary in insight-ui at: https://github.com/bitpay/insight-ui/blob/master/public/src/js/controllers/index.js#L10-17
