### ISSUE TITLE
Can't consume socket.io API.

### ISSUE THREAD

**Issue by maltese** [bitpay/insight-api#158]
Hi,

I successfully managed to set up and sync an instance of insight-api.

However, I can't find a way to test the socket.io API.

I downloaded the socket.io javascript library and I've created a simple html page loading that script and executing the following one:

``` javascript
var socket = io.connect("ws://myserver.local:3000/socket.io/1/")
socket.on('tx', function(data) {
    console.log(data)
})
```

When I open the page in Safari or Chrome the server is simply flooded with requests (maybe even 100 per second). The server always responds with "Welcome to socket.io".

What am I doing wrong client-side?

**Comment by doged** [comment]
@maltese can you please paste fix for client side test?

im using 

<html>
<body>
    <script src="http://darkchain.link/socket.io/socket.io.js"></script>
    <script>
        var socket = io("http://darkchain.link/");
        socket.on('connect', function() {
            console.log("connected!")
            socket.on('tx', function(t) {
                console.log("Did receive transaction!")
            })
        })
    </script>
</body>
</html>

**Comment by doged** [comment]
got it! thanks for posting this issue though, helped.

socket.emit('subscribe', 'inv');
