### ISSUE TITLE
Perpetual NPM install issues

### ISSUE THREAD

**Issue by SodaWarz** [bitpay/insight-api#162]
Been trying for over a week to get insight installed but cannot get past the NPM install 

i get the following errors plus about 1,000 more,

C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(356): error C3861:
 'New': identifier not found [C:\insight-api\node_modules\leveldown\build\level
down.vcxproj]
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(360): error C2039:
 'ThrowException' : is not a member of 'v8' [C:\insight-api\node_modules\leveld
own\build\leveldown.vcxproj]
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(360): error C2039:
 'New' : is not a member of 'v8::String' [C:\insight-api\node_modules\leveldown
\build\leveldown.vcxproj]
          C:\Users\Administrator\.node-gyp\0.11.13\deps\v8\include\v8.h(1661) :
   see declaration of 'v8::String'
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(360): error C3861:
 'ThrowException': identifier not found [C:\insight-api\node_modules\leveldown\
build\leveldown.vcxproj]
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(360): error C3861:
 'New': identifier not found [C:\insight-api\node_modules\leveldown\build\level
down.vcxproj]
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(668): error C2660:
 'v8::Object::New' : function does not take 0 arguments [C:\insight-api\node_mo
dules\leveldown\build\leveldown.vcxproj]
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(669): error C2039:
 'NewSymbol' : is not a member of 'v8::String' [C:\insight-api\node_modules\lev
eldown\build\leveldown.vcxproj]
          C:\Users\Administrator\.node-gyp\0.11.13\deps\v8\include\v8.h(1661) :
   see declaration of 'v8::String'
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(669): error C3861:
 'NewSymbol': identifier not found [C:\insight-api\node_modules\leveldown\build
\leveldown.vcxproj]
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(675): error C2039:
 'Dispose' : is not a member of 'v8::Persistent<T>' [C:\insight-api\node_module
s\leveldown\build\leveldown.vcxproj]
          with
          [
              T=v8::Object
          ]
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(676): error C2039:
 'Clear' : is not a member of 'v8::Persistent<T>' [C:\insight-api\node_modules\
leveldown\build\leveldown.vcxproj]
          with
          [
              T=v8::Object
          ]
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(680): error C2039:
 'NewSymbol' : is not a member of 'v8::String' [C:\insight-api\node_modules\lev
eldown\build\leveldown.vcxproj]
          C:\Users\Administrator\.node-gyp\0.11.13\deps\v8\include\v8.h(1661) :
   see declaration of 'v8::String'
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(681): error C2228:
 left of '.As' must have class/struct/union [C:\insight-api\node_modules\leveld
own\build\leveldown.vcxproj]
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(681): error C2059:
 syntax error : ')' [C:\insight-api\node_modules\leveldown\build\leveldown.vcxp
roj]
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(693): error C2039:
 'NewSymbol' : is not a member of 'v8::String' [C:\insight-api\node_modules\lev
eldown\build\leveldown.vcxproj]
          C:\Users\Administrator\.node-gyp\0.11.13\deps\v8\include\v8.h(1661) :
   see declaration of 'v8::String'
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(693): error C2228:
 left of '.As' must have class/struct/union [C:\insight-api\node_modules\leveld
own\build\leveldown.vcxproj]
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(693): error C2059:
 syntax error : ')' [C:\insight-api\node_modules\leveldown\build\leveldown.vcxp
roj]
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(695): error C2039:
 'GetCurrent' : is not a member of 'v8::Context' [C:\insight-api\node_modules\l
eveldown\build\leveldown.vcxproj]
          C:\Users\Administrator\.node-gyp\0.11.13\deps\v8\include\v8.h(5177) :
   see declaration of 'v8::Context'
c:\insight-api\node_modules\leveldown\src\async.h(24): error C2660: 'v8::Object
::New' : function does not take 0 arguments [C:\insight-api\node_modules\leveld
own\build\leveldown.vcxproj]
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(695): error C2227:
 left of '->Global' must point to class/struct/union/generic type [C:\insight-a
pi\node_modules\leveldown\build\leveldown.vcxproj]
          type is ''unknown-type''
c:\insight-api\node_modules\leveldown\src\database.h(27): error C2660: 'v8::Obj
ect::New' : function does not take 0 arguments [C:\insight-api\node_modules\lev
eldown\build\leveldown.vcxproj]
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(699): error C2661:
 'node::MakeCallback' : no overloaded function takes 4 arguments [C:\insight-ap
i\node_modules\leveldown\build\leveldown.vcxproj]
c:\insight-api\node_modules\leveldown\src\database.h(28): error C2039: 'NewSymb
ol' : is not a member of 'v8::String' [C:\insight-api\node_modules\leveldown\bu
ild\leveldown.vcxproj]
          C:\Users\Administrator\.node-gyp\0.11.13\deps\v8\include\v8.h(1661) :
   see declaration of 'v8::String'
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(693): error C3861:
 'NewSymbol': identifier not found [C:\insight-api\node_modules\leveldown\build
\leveldown.vcxproj]
c:\insight-api\node_modules\leveldown\src\database.h(28): error C3861: 'NewSymb
ol': identifier not found [C:\insight-api\node_modules\leveldown\build\leveldow
n.vcxproj]
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(695): error C3861:
 'GetCurrent': identifier not found [C:\insight-api\node_modules\leveldown\buil
d\leveldown.vcxproj]
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(739): error C2039:
 'NewSymbol' : is not a member of 'v8::String' [C:\insight-api\node_modules\lev
eldown\build\leveldown.vcxproj]
          C:\Users\Administrator\.node-gyp\0.11.13\deps\v8\include\v8.h(1661) :
   see declaration of 'v8::String'
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(739): error C3861:
 'NewSymbol': identifier not found [C:\insight-api\node_modules\leveldown\build
\leveldown.vcxproj]
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(746): error C2039:
 'NewSymbol' : is not a member of 'v8::String' [C:\insight-api\node_modules\lev
eldown\build\leveldown.vcxproj]
          C:\Users\Administrator\.node-gyp\0.11.13\deps\v8\include\v8.h(1661) :
   see declaration of 'v8::String'
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(746): error C2228:
 left of '.As' must have class/struct/union [C:\insight-api\node_modules\leveld
own\build\leveldown.vcxproj]
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(746): error C2059:
 syntax error : ')' [C:\insight-api\node_modules\leveldown\build\leveldown.vcxp
roj]
..\src\leveldown.cc(82): error C2664: 'v8::FunctionTemplate::New' : cannot conv
ert parameter 1 from 'void (__cdecl *)(const v8::FunctionCallbackInfo<T> &)' to
 'v8::Isolate *' [C:\insight-api\node_modules\leveldown\build\leveldown.vcxproj
]
          with
          [
              T=v8::Value
          ]
          There is no context in which this conversion is possible
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(768): error C2039:
 'New' : is not a member of 'v8::String' [C:\insight-api\node_modules\leveldown
\build\leveldown.vcxproj]
          C:\Users\Administrator\.node-gyp\0.11.13\deps\v8\include\v8.h(1661) :
   see declaration of 'v8::String'
..\src\leveldown.cc(82): error C2227: left of '->GetFunction' must point to cla
ss/struct/union/generic type [C:\insight-api\node_modules\leveldown\build\level
down.vcxproj]
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(769): error C2466:
 cannot allocate an array of constant size 0 [C:\insight-api\node_modules\level
down\build\leveldown.vcxproj]
..\src\leveldown.cc(85): error C2039: 'NewSymbol' : is not a member of 'v8::Str
ing' [C:\insight-api\node_modules\leveldown\build\leveldown.vcxproj]
          C:\Users\Administrator\.node-gyp\0.11.13\deps\v8\include\v8.h(1661) :
   see declaration of 'v8::String'
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(769): error C2440:
 'initializing' : cannot convert from 'int' to 'v8::Local<T>' [C:\insight-api\n
ode_modules\leveldown\build\leveldown.vcxproj]
          with
          [
              T=v8::Value
          ]
          No constructor could take the source type, or constructor overload re
  solution was ambiguous
..\src\leveldown.cc(86): error C2664: 'v8::FunctionTemplate::New' : cannot conv
ert parameter 1 from 'void (__cdecl *)(const v8::FunctionCallbackInfo<T> &)' to
 'v8::Isolate *' [C:\insight-api\node_modules\leveldown\build\leveldown.vcxproj
]
          with
          [
              T=v8::Value
          ]
          There is no context in which this conversion is possible
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(768): error C3861:
 'New': identifier not found [C:\insight-api\node_modules\leveldown\build\level
down.vcxproj]
..\src\leveldown.cc(86): error C2227: left of '->GetFunction' must point to cla
ss/struct/union/generic type [C:\insight-api\node_modules\leveldown\build\level
down.vcxproj]
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(987): error C2039:
 'AsciiValue' : is not a member of 'v8::String' [C:\insight-api\node_modules\le
veldown\build\leveldown.vcxproj]
          C:\Users\Administrator\.node-gyp\0.11.13\deps\v8\include\v8.h(1661) :
   see declaration of 'v8::String'
..\src\leveldown.cc(85): error C3861: 'NewSymbol': identifier not found [C:\ins
ight-api\node_modules\leveldown\build\leveldown.vcxproj]
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(987): error C2065:
 'AsciiValue' : undeclared identifier [C:\insight-api\node_modules\leveldown\bu
ild\leveldown.vcxproj]
..\src\leveldown.cc(90): error C2039: 'NewSymbol' : is not a member of 'v8::Str
ing' [C:\insight-api\node_modules\leveldown\build\leveldown.vcxproj]
          C:\Users\Administrator\.node-gyp\0.11.13\deps\v8\include\v8.h(1661) :
   see declaration of 'v8::String'
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(987): error C2146:
 syntax error : missing ';' before identifier 'value' [C:\insight-api\node_modu
les\leveldown\build\leveldown.vcxproj]
..\src\leveldown.cc(91): error C2664: 'v8::FunctionTemplate::New' : cannot conv
ert parameter 1 from 'void (__cdecl *)(const v8::FunctionCallbackInfo<T> &)' to
 'v8::Isolate *' [C:\insight-api\node_modules\leveldown\build\leveldown.vcxproj
]
          with
          [
              T=v8::Value
          ]
          There is no context in which this conversion is possible
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(987): error C3861:
 'value': identifier not found [C:\insight-api\node_modules\leveldown\build\lev
eldown.vcxproj]
..\src\leveldown.cc(91): error C2227: left of '->GetFunction' must point to cla
ss/struct/union/generic type [C:\insight-api\node_modules\leveldown\build\level
down.vcxproj]
..\src\leveldown.cc(90): error C3861: 'NewSymbol': identifier not found [C:\ins
ight-api\node_modules\leveldown\build\leveldown.vcxproj]
..\src\leveldown.cc(94): error C2039: 'NewSymbol' : is not a member of 'v8::Str
ing' [C:\insight-api\node_modules\leveldown\build\leveldown.vcxproj]
          C:\Users\Administrator\.node-gyp\0.11.13\deps\v8\include\v8.h(1661) :
   see declaration of 'v8::String'
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(1050): error C2065
: 'value' : undeclared identifier [C:\insight-api\node_modules\leveldown\build\
leveldown.vcxproj]
..\src\leveldown.cc(94): error C3861: 'NewSymbol': identifier not found [C:\ins
ight-api\node_modules\leveldown\build\leveldown.vcxproj]
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(1058): error C2065
: 'value' : undeclared identifier [C:\insight-api\node_modules\leveldown\build\
leveldown.vcxproj]
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(1058): error C2065
: 'value' : undeclared identifier [C:\insight-api\node_modules\leveldown\build\
leveldown.vcxproj]
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(1058): error C2228
: left of '.length' must have class/struct/union [C:\insight-api\node_modules\l
eveldown\build\leveldown.vcxproj]
          type is ''unknown-type''
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(1091): error C2065
: 'value' : undeclared identifier [C:\insight-api\node_modules\leveldown\build\
leveldown.vcxproj]
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(1091): error C2065
: 'value' : undeclared identifier [C:\insight-api\node_modules\leveldown\build\
leveldown.vcxproj]
C:\insight-api\node_modules\leveldown\node_modules\nan\nan.h(1091): error C2228
: left of '.length' must have class/struct/union [C:\insight-api\node_modules\l
eveldown\build\leveldown.vcxproj]
          type is ''unknown-type''
c:\insight-api\node_modules\leveldown\src\leveldown.h(26): error C2039: 'NewSym
bol' : is not a member of 'v8::String' [C:\insight-api\node_modules\leveldown\b
uild\leveldown.vcxproj]
          C:\Users\Administrator\.node-gyp\0.11.13\deps\v8\include\v8.h(1661) :
   see declaration of 'v8::String'
c:\insight-api\node_modules\leveldown\src\leveldown.h(26): error C3861: 'NewSym
bol': identifier not found [C:\insight-api\node_modules\leveldown\build\leveldo
wn.vcxproj]
c:\insight-api\node_modules\leveldown\src\database.h(27): error C2660: 'v8::Obj
ect::New' : function does not take 0 arguments [C:\insight-api\node_modules\lev
eldown\build\leveldown.vcxproj]
c:\insight-api\node_modules\leveldown\src\database.h(28): error C2039: 'NewSymb
ol' : is not a member of 'v8::String' [C:\insight-api\node_modules\leveldown\bu
ild\leveldown.vcxproj]
          C:\Users\Administrator\.node-gyp\0.11.13\deps\v8\include\v8.h(1661) :
   see declaration of 'v8::String'
c:\insight-api\node_modules\leveldown\src\database.h(28): error C3861: 'NewSymb
ol': identifier not found [C:\insight-api\node_modules\leveldown\build\leveldow
n.vcxproj]
c:\insight-api\node_modules\leveldown\src\async.h(24): error C2660: 'v8::Object
::New' : function does not take 0 arguments [C:\insight-api\node_modules\leveld
own\build\leveldown.vcxproj]

I also get this error or rather warning when i first initiate the install

nmp warn excluding symbolic link examples\PayPro\bitcore.js -> ../../browser/bundle.js

I have updated node.js, installed visual studio, double checked the windows sdk, doublechecked openssl, i am totally lost.

The OS is windows server 2012 datacenter, python is installed, any help would be appreciated.

**Comment by braydonf** [comment]
This was likely caused because of using an unsupported Node.js version, however is no longer relevant with 0.3.0.
