### ISSUE TITLE
Block time is inconsistent

### ISSUE THREAD

**Issue by iancoleman** [bitpay/insight-api#169]
The time of blocks is inconsistent.

eg for block at height `317869` (hash `00000000000000000a3b5fc05aad1b24601a9b5737fccee60e47c78250059054`)

Time is `1409212111` for `/api/block/[:hash]`
Time is `1409212015` for `/api/blocks`

My unconfirmed suspicion is this happens because `/api/block/[:hash]` uses the [block timestamp](https://en.bitcoin.it/wiki/Block_timestamp), whereas `/api/blocks` uses the system time when the block is received. This is based on comparing two different installations: `/api/block/[:hash]` has the same timestamp on both installations, but `/api/blocks` does not.

I suggest the timestamp on `/api/blocks` should also be the block timestamp.

It's worth noting that transaction times use the block timestamp (which seems to be the correct way of doing it).

**Comment by braydonf** [comment]
This is resolved on latest master, and with bitcore-node.
