### ISSUE TITLE
insight randomly stops syncing. after deleting the DB and resyncing, it doesn't complete the sync

### ISSUE THREAD

**Issue by robby-d** [bitpay/insight-api#17]
Here's the log: http://pastebin.com/gndf7zFK

Odd that it says it's at 98.x%, and says it's done syncing ... I'm thinking I may have corrupted testnet data (I'm going to pull over from another server).

This is with the newest version. I also reran npm install, etc.

**Comment by abstream** [comment]
@robby-dermody what was your final solution for insight-api out of sync problem?
I experience the very same issue and my first thought was to regularly restart insight no matter of the last block hash. any help is appreciated.

Thanks.

**Comment by abstream** [comment]
@matiu /api/status?q=getLastBlockHash  now return 2 values: syncTipHash , lastblockhash
shall i conclude that something is wrong if those values are different?

**Comment by robby-dermody** [comment]
@abstream in our case an update to the newest master fixed it, I believe. We might had had to resync/rebuild the db as well... It's been awhile and my memory is fuzzy on this

**Comment by abstream** [comment]
@robby-dermody , just to put info for others interested on the topic,
I got the code yesterday with this command: 

git clone https://github.com/bitpay/insight-api && cd insight-api

so, I guess it is up to date. I managed to get rid off the issue by setting both p2p port and b_port to 9332 (using litecoin at the moment). Now insight syncs fine, does not disconnect, but i intend to check regulary(cron + email) /api/peer and act manually if needed.

**Comment by abstream** [comment]
Ok, i shouldn't celebrate so soon....after changing the ports it stopped to disconnect me but the sync still stops after 100% are reached. It would not update...it just considers that 100% are reached and one need to restart the api in order to resync... i cannot call util/sync.js while the api is running cause it is locked

**Comment by 9cat** [comment]
I am still encounter this problem when version insight API v0.2.12
