### ISSUE TITLE
Transactions are not ordered correctly by block height

### ISSUE THREAD

**Issue by Nd60** [bitpay/insight-api#175]
Some transactions are not ordered correctly by block height.

For example, I have chosen the address 1AyRmvqe99mRWU69w8Hbaeej8twMpdeiKm

When I call /api/addr/1AyRmvqe99mRWU69w8Hbaeej8twMpdeiKm , https://insight.bitpay.com/address/1AyRmvqe99mRWU69w8Hbaeej8twMpdeiKm and https://insight.bitpay.com/api/txs?address=1AyRmvqe99mRWU69w8Hbaeej8twMpdeiKm&pageNum=0 , the first four returned txids show up in this order:

f208af7d7413186b6b552372385ed300e5ce1eaeb2668c2f37a4c342c8380a62
4cb6e36e538c9f86ad0a0794920149a060458005de27a7aaebc51ce28d9364bb
8b36c2981d8880da18de010966b9c65d1a0dcaa4ede270ec687d1da5407d0417
c1e40845b6d1618d02fcfd9ca9fe145216222e248097bab0b7825ba7dcaf23cc

However,

f208af7d7413186b6b552372385ed300e5ce1eaeb2668c2f37a4c342c8380a62 appears in block 318379
4cb6e36e538c9f86ad0a0794920149a060458005de27a7aaebc51ce28d9364bb appears in block 318320
8b36c2981d8880da18de010966b9c65d1a0dcaa4ede270ec687d1da5407d0417 appears in block 318322
c1e40845b6d1618d02fcfd9ca9fe145216222e248097bab0b7825ba7dcaf23cc appears in block 318320

and the correct order should be:
f208af7d7413186b6b552372385ed300e5ce1eaeb2668c2f37a4c342c8380a62
8b36c2981d8880da18de010966b9c65d1a0dcaa4ede270ec687d1da5407d0417
c1e40845b6d1618d02fcfd9ca9fe145216222e248097bab0b7825ba7dcaf23cc
4cb6e36e538c9f86ad0a0794920149a060458005de27a7aaebc51ce28d9364bb

I also want to tell you that the insight-api is really helpful. Keep up the good work!

**Comment by braydonf** [comment]
Transactions are ordered by block height now.
