### ISSUE TITLE
Cannot get block info, does not rollback

### ISSUE THREAD

**Issue by antanst** [bitpay/insight-api#187]
My insight-api instance does not seem to be able to rollback to a valid block from an invalid one:

```
info: starting...
insight server listening on port 3000 in development mode
info: Previous TIP is now orphan. Back to:undefined

/Users/username/insight/node_modules/insight-bitcore-api/lib/BlockDb.js:119
      throw new Error('unable to get info for block:'+ hash);
            ^
Error: unable to get info for block:00000000000000072353dfe8b7f45d97fd2d2a9d16809279dc8d30e4d7155b3a
    at /Users/username/insight/node_modules/insight-bitcore-api/lib/BlockDb.js:119:13
    at /Users/username/insight/node_modules/insight-bitcore-api/lib/BlockDb.js:280:30
    at /Users/username/insight/node_modules/insight-bitcore-api/lib/Rpc.js:88:40
    at IncomingMessage.<anonymous> (/Users/username/insight/node_modules/insight-bitcore-api/node_modules/bitcore/lib/RpcClient.js:189:7)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)

npm ERR! insight-bitcore@0.2.3 start: `INSIGHT_PUBLIC_PATH=public node node_modules/.bin/insight-bitcore-api`
npm ERR! Exit status 8
npm ERR! 

```

The block 00000000000000072353dfe8b7f45d97fd2d2a9d16809279dc8d30e4d7155b3a does not exist when querying bitcoind.

npm-debug.log does not have any more useful info.

**Comment by nanocoinorg** [comment]
If you can sync via the RPC still then it is most likely caused by the hard coded SHA256 conversion when reading from the data files. You either need to match that to your algorithm of choice or write in a switch that forces it to always use the RPC.

**Comment by posita** [comment]
This is something that probably needs to be properly addressed within insight. Blocks can disappear from `bitcoind` when a new chain is derived. Forks happen. Consider the following:

* sync `bitcoind` (`bitcoind` believes chain A is the main chain)
* start insight
* stop insight for maintenance
* stop `bitcoind` for maintenance
* consensus is achieved that chain B is the main chain
* start `bitcoind` and wait for sync (`bitcoind` now believes chain B is the main chain; chain A's blocks are no longer valid)
* start insight

At this point, insight will be hosed and require a complete rebuild, even though everything has worked as it should on all lower levels.

I don't know what will happen if a swap from A to B happens while everything is running, but I'm pretty sure that insight's start-up process is too brittle should the swap happen between insight's last and current restarts.

Possible duplicates
* #596
* #627

**Comment by troggy** [comment]
same here

**Comment by braydonf** [comment]
Outdated

**Comment by RakibFiha** [comment]
Cannot GET /insight-api
I am trying to run zen insight api
