### ISSUE TITLE
Error! Can't connect to bitcoind to get live updates from the p2p network. (Tried connecting to bitcoind at 127.0.0.1:9348 and failed.)

### ISSUE THREAD

**Issue by OmarxGx** [bitpay/insight-api#193]
So this is the exact message I'm getting from running the Insight Explorer set up for Hirocoin.

Error!
Can't connect to bitcoind to get live updates from the p2p network. (Tried connecting to bitcoind at 127.0.0.1:9348 and failed.)

I also notice that while it syncs correctly to 100% it spits out this message 
{ '0': 'connecting to 127.0.0.1:9348' }
{ '0': 'disconnected from peer 127.0.0.1:9348' }

Any ideas?

**Comment by doged** [comment]
i have the correct magic.. but my p2p still wont connect.. see my specifics here:
https://github.com/bitpay/insight-api/issues/327

if anyone can lend a hand ill gladly tip, its been driving me crazy.
