### ISSUE TITLE
Many Transactions are missing

### ISSUE THREAD

**Issue by nikos-glikis** [bitpay/insight-api#194]
I installed the api, It all looks ok, inithial synchronization is done, and now it is running.

Although there are some transactions missing fro the database.

When I query: http://mydomain:3000/api/tx/acd17beba5aa26313f66d14ff65b782db21e8452d1b9c32ca5227c88df4f07d5
I get a response "Not found" and a 404 response code.

This is a valid transaction:  https://insight.bitpay.com/tx/acd17beba5aa26313f66d14ff65b782db21e8452d1b9c32ca5227c88df4f07d5

The database is completely synced. 

I installed it 2 nights ago, I have the latest version.

Any ideas why this is happening ?

I don't know if this is related, but the transactions I check are very recent.

Thanks

**Comment by srw** [comment]
I have the same issue in two servers. Both running bitcoind 0.9.4.

What version of bitcoind are you using on https://insight.bitpay.com/ ?

**Comment by fanatid** [comment]
You can see information about bitcoind on the next url: https://insight.bitpay.com/api/status?q=getInfo
For now it is: 
```
{ info: 
   { version: 99900,
     protocolversion: 70002,
     walletversion: 60000,
     balance: 0,
     blocks: 349598,
     timeoffset: 18,
     connections: 9,
     proxy: '',
     difficulty: 46717549644.70642,
     testnet: false,
     keypoololdest: 1396372818,
     keypoolsize: 101,
     paytxfee: 0,
     relayfee: 0.00001,
     errors: 'This is a pre-release test build - use at your own risk - do not use for mining or merchant applications' } }
```
