### ISSUE TITLE
TypeError: Cannot read property 'info' of undefined

### ISSUE THREAD

**Issue by OmarxGx** [bitpay/insight-api#195]
/home/omar/insight/node_modules/insight-bitcore-api/app/controllers/blocks.js:63
    if (!block.info) {
              ^
TypeError: Cannot read property 'info' of undefined
    at /home/omar/insight/node_modules/insight-bitcore-api/app/controllers/blocks.js:63:15
    at /home/omar/insight/node_modules/insight-bitcore-api/lib/BlockDb.js:279:30
    at /home/omar/insight/node_modules/insight-bitcore-api/lib/Rpc.js:88:40
    at IncomingMessage.<anonymous> (/home/omar/insight/node_modules/insight-bitcore-api/node_modules/bitcore/lib/RpcClient.js:203:7)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

This is a new error I'm receiving after getting the P2P to connect. I cleared all the folders in ./insight and ran sync -D on Insight-API and it successfully synced to 100%. However I get this message when syncing Insight and eventually it appears on Insight-API and gives me this message 

npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0

**Comment by braydonf** [comment]
Outdated
