### ISSUE TITLE
Query Times? Variables? STUCK !

### ISSUE THREAD

**Issue by SodaWarz** [bitpay/insight-api#208]
Having some difficulty figuring out why of 3 machines running insight, the worst one in terms of hardware is running the fastest queries on the API.

I have built an application which runs on the Insight API, it runs about a million requests every time it is run. (/api/addr/ADDRESS/balance) Each machine runs the java application in windows and insight is hosted in a VM. of 3 machines the worst machine in terms of hardware is running 1-2ms queries, the fastest machine with 4x the ram and 8x the processor is running 150-500ms queries.

I am a little confused as every VM has the same resources allocated to it.

Is there some sort of variable in the source i need to configure to speed the query time up on the other machines? How did my worst machine end up running the fastest? Does anyone have any insight as to why this is happening?

**Comment by braydonf** [comment]
Closing as this is outdated/stale at this point. Though I wonder were you querying over a network?
