### ISSUE TITLE
Loosing p2p connection

### ISSUE THREAD

**Issue by rentodev** [bitpay/insight-api#211]
Insight on start makes initial P2P connection to node, but then after about 60 seconds disconnects.

Looking at coin node's debug.log I see following:

```
accepted connection 127.0.0.1:59973

PROCESSMESSAGE MESSAGESTART NOT FOUND

socket no message in first 60 seconds, 1 0
disconnecting node 127.0.0.1:59973
```

Any idea's what might be the cause of this issue here?

**Comment by braydonf** [comment]
No longer relevant as bitcoind is running in the same process.
