### ISSUE TITLE
Improve memory usage

### ISSUE THREAD

**Issue by cmgustavo** [bitpay/insight-api#229]
```
[livenet-19 (err) 2014-11-02T05:24:59] FATAL ERROR: CALL_AND_RETRY_2 Allocation failed - process out of memory
```

Livenet consumes lots of memory. In just 22 hours the memory usage was 3.5GB

**Comment by braydonf** [comment]
Memory issues should be resolved, with these exceptions:
- https://github.com/bitpay/insight-api/issues/418
- https://github.com/bitpay/bitcore-node/issues/354
