### ISSUE TITLE
/api/sync status:finished , blockChainHeight not current

### ISSUE THREAD

**Issue by alexanderkent** [bitpay/insight-api#230]
Installed the API, looks great, but wondering about /api/sync -- should it reflect the current blockChainHeight and continuously update after the initial sync?

**Comment by abstream** [comment]
This is relvant to https://github.com/bitpay/insight-api/issues/17 , I think, isn't it?
My experience - it is disconnected from the coin daemon after full sync.. i need to restart insight api, it will sync again and again get disconected

**Comment by doged** [comment]
yeah im having an issue where /api/status?q=getInfo is working, but sync only occurs from rpc, and p2p doesnt connect, so im not getting live updates. not sure why my p2p wont connect. i can open it from telnet.

**Comment by braydonf** [comment]
Closing as outdated. FYI, both `blockChainHeight` and  `height` now give the same value, as indexes are in bitcoind, the height will be updated with zmq hashblock events.
