### ISSUE TITLE
Run a day and then crash

### ISSUE THREAD

**Issue by terrylai** [bitpay/insight-api#261]
Hello all,

I run insight for a day and then encounter crashing. It is not the first time and I met it several times before. 

The log is as in the following:

/root/insight/node_modules/insight-bitcore-api/lib/Sync.js:145
            if (err) throw err;
                           ^
Error: Could not found block:9b47b129653843497ea917ca38f080ace5c51e1286053e3dcf969b84ec39c3cc
    at /root/insight/node_modules/insight-bitcore-api/lib/Sync.js:193:22
    at /root/insight/node_modules/insight-bitcore-api/lib/BlockDb.js:227:12
    at dispatchError (/root/insight/node_modules/insight-bitcore-api/node_modules/levelup/lib/util.js:77:7)
    at /root/insight/node_modules/insight-bitcore-api/node_modules/levelup/lib/levelup.js:222:14

npm ERR! insight-bitcore@0.2.5 start: `INSIGHT_PUBLIC_PATH=public node node_modules/.bin/insight-bitcore-api`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the insight-bitcore@0.2.5 start script.
npm ERR! This is most likely a problem with the insight-bitcore package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     INSIGHT_PUBLIC_PATH=public node node_modules/.bin/insight-bitcore-api
npm ERR! You can get their info via:
npm ERR!     npm owner ls insight-bitcore
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.5-x86_64-linode46
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! cwd /root/insight
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/insight/npm-debug.log
npm ERR! not ok code 0
root@localhost:~# 

Could anyone kindly teach me how to do?

**Comment by braydonf** [comment]
Can you try with the latest https://bitcore.io/guides/full-node as this is now outdated.
