### ISSUE TITLE
endpoint /api/status?q=getTxOutSetInfo is always super slow compared to all the other API methods

### ISSUE THREAD

**Issue by moredore123** [bitpay/insight-api#265]
Why is https://insight.bitpay.com/api/status?q=getTxOutSetInfo endpoint so slow to give me a response? The reason is because I want a one call api method that gives me the block height similar to what blockchain.info have with there endpoint https://blockchain.info/q/getblockcount.

**Comment by braydonf** [comment]
This method has been deprecated, since the underlying call is very slow.
