### ISSUE TITLE
different balances from some addresses

### ISSUE THREAD

**Issue by RCasatta** [bitpay/insight-api#266]
Hi,

in this moment i see some differences from these balances
https://blockchain.info/address/1G5mKz3p2LD4s7tWTVX5X54oAm71FouJac
balance=0

https://insight.bitpay.com/address/1G5mKz3p2LD4s7tWTVX5X54oAm71FouJac
balance=220 bits

and
https://blockchain.info/address/1GiiDUPpTcmyLaaLPeMtKtRmtudBA1fZPa
balance=400 bits
https://insight.bitpay.com/address/1GiiDUPpTcmyLaaLPeMtKtRmtudBA1fZPa
balance=0 (but there are 400bits unconfirmed, but the transaction is really old)

**Comment by braydonf** [comment]
These are showing the same.
