### ISSUE TITLE
Insight and Bitcoind.js

### ISSUE THREAD

**Issue by chjj** [bitpay/insight-api#269]
The goal of bitcoind.js is to get it into insight and potentially even bitcore(optionally). I've recently [rebased libbitcoind.so][1] onto the latest master of [bitcoin][2]. So that's pretty nice - there were a lot of build changes in the past month or two. I'm going to start rebasing regularly so libbitcoind users can always use the latest and greatest.

I've [begun to implement bitcoind.js into insight-api][3], but it's really divorced from what insight-api is. Insight maintains its own leveldb, and assumes this along with numerous other caches. The way I see this working is to rewrite insight completely, aside from the frontend. My attempts at modifying the current code are not very elegant, although there was good that came out of these attempts: I ended up writing a few more functions in bitcoind.js that will make it more useful as a blockchain explorer.

I'm going to review this code a lot and make a hard fork of it. It may not resemble the original insight-api very much.

cc @gasteve @maraoz @matiu

[1]: https://github.com/bitpay/bitcoin/commit/8ef55c8fd1c4e14f2cc99d85f85207e33ae0336a
[2]: https://github.com/bitcoin/bitcoin
[3]: https://github.com/chjj/insight-api/tree/bitcoind.js/lib

**Comment by braydonf** [comment]
The branch https://github.com/bitpay/insight-api/tree/v0.3.0 currently has Insight working with Bitcore Node (Bitcoind.js)

**Comment by maraoz** [comment]
Nice!! I'll test it out and let you know

**Comment by braydonf** [comment]
The setup process needs to be smoothed out, however, it should resemble:
```
npm install -g bitcore-node@0.2.0-beta.5
bitcore-node create mynode
cd mynode
bitcore-node add https://github.com/bitpay/insight-api#v0.3.0
bitcore-node start
```

Still need to:
- Fix bug with CLI so the add command works: https://github.com/bitpay/bitcore-node/pull/184
- Add the name of the service correctly into `bitcore-node.json` (currently needs to be added/fixed manually)

**Comment by braydonf** [comment]
Finished, and now both are working together: https://github.com/bitpay/bitcore
