### ISSUE TITLE
It is not able to install this API on Windows

### ISSUE THREAD

**Issue by iivanov2** [bitpay/insight-api#271]
I tried to install it on Windows (includind Windows 7x64; Windows 7x86; Windows 8.1x86) without success. I recieved many errors during installation process.
Your instructions for Windows installation are not good, please write how to install your api on Windows from scratch because I'm triyng from 2 days and I get errors whatever I tried.
I tried this: http://counterparty.io/docs/build-system/set-up-insight/
and this: https://github.com/TooTallNate/node-gyp/wiki/Visual-Studio-2010-Setup
and more, but I got crazy errors every time.

This is part from last installation attemp log:

C:\>git clone https://github.com/bitpay/insight-api.git
Cloning into 'insight-api'...
remote: Counting objects: 8222, done.
remote: Compressing objects:  33% (4/12)   Receiving objects:   4% (329/8222)
remote: Compressing objects: 100% (12/12), done.
remote: Total 8222 (delta 4), reused 0 (delta 0) eceiving objects:  99% (8140/82
Receiving objects: 100% (8222/8222), 2.27 MiB | 407.00 KiB/s, done.
Resolving deltas: 100% (4944/4944), done.

Checking connectivity... done.
Checking out files: 100% (105/105), done.

C:\>cd C:\insight-api

C:\insight-api>npm install
npm WARN excluding symbolic link examples\PayPro\bitcore.js -> ../../browser/bun
dle.js
\

> buffertools@2.1.2 install C:\insight-api\node_modules\buffertools
> node-gyp rebuild

/
C:\insight-api\node_modules\buffertools>node "C:\Program Files\nodejs\node_modul
es\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  buffertools.cc
C4530: C++ exception handler used, but unwind semantics are not enabled. Specif
y /EHsc [C:\insight-api\node_modules\buffertools\build\buffertools.vcxproj]
C:\Users\Iskren\.node-gyp\0.10.33\deps\v8\include\v8.h(179): warning C4506: no
definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Ha
ndle<T>)' [C:\insight-api\node_modules\buffertools\build\buffertools.vcxproj]
          with
          [
              T=v8::Object
          ]
     Creating library C:\insight-api\node_modules\buffertools\build\Release\buf
  fertools.lib and object C:\insight-api\node_modules\buffertools\build\Release
  \buffertools.exp
  Generating code
  Finished generating code
  buffertools.vcxproj -> C:\insight-api\node_modules\buffertools\build\Release\
  \buffertools.node
-

> base58-native@0.1.2 install C:\insight-api\node_modules\base58-native
> node-gyp rebuild

\
C:\insight-api\node_modules\base58-native>node "C:\Program Files\nodejs\node_mod
ules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild

Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  base58.cc
C:\Users\Iskren\.node-gyp\0.10.33\deps\v8\include\v8.h(184): warning C4506: no
definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Ha
ndle<T>)' [C:\insight-api\node_modules\base58-native\build\base58.vcxproj]
          with
          [
              T=v8::Object
          ]
     Creating library C:\insight-api\node_modules\base58-native\build\Release\b
  ase58.lib and object C:\insight-api\node_modules\base58-native\build\Release\
  base58.exp
base58.obj : error LNK2001: unresolved external symbol _BN_free [C:\insight-api
\node_modules\base58-native\build\base58.vcxproj]
base58.obj : error LNK2001: unresolved external symbol _BN_num_bits [C:\insight
-api\node_modules\base58-native\build\base58.vcxproj]
base58.obj : error LNK2001: unresolved external symbol _BN_mul [C:\insight-api\
node_modules\base58-native\build\base58.vcxproj]
base58.obj : error LNK2001: unresolved external symbol _BN_add [C:\insight-api\
node_modules\base58-native\build\base58.vcxproj]
base58.obj : error LNK2001: unresolved external symbol _BN_cmp [C:\insight-api\
node_modules\base58-native\build\base58.vcxproj]
base58.obj : error LNK2001: unresolved external symbol _BN_get_word [C:\insight
-api\node_modules\base58-native\build\base58.vcxproj]
-api\node_modules\base58-native\build\base58.vcxproj]ol _BN_set_word [C:\insight
base58.obj : error LNK2001: unresolved external symbol _BN_div [C:\insight-api\
node_modules\base58-native\build\base58.vcxproj]
base58.obj : error LNK2001: unresolved external symbol _BN_new [C:\insight-api\
node_modules\base58-native\build\base58.vcxproj]
base58.obj : error LNK2001: unresolved external symbol _BN_bn2bin [C:\insight-a
pi\node_modules\base58-native\build\base58.vcxproj]
api\node_modules\base58-native\build\base58.vcxproj]bol _BN_CTX_new [C:\insight-
base58.obj : error LNK2001: unresolved external symbol _BN_CTX_free [C:\insight
-api\node_modules\base58-native\build\base58.vcxproj]
base58.obj : error LNK2001: unresolved external symbol _BN_bin2bn [C:\insight-a
pi\node_modules\base58-native\build\base58.vcxproj]
C:\insight-api\node_modules\base58-native\build\Release\base58.node : fatal err
or LNK1120: 13 unresolved externals [C:\insight-api\node_modules\base58-native\
build\base58.vcxproj]
\gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:
12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\insight-api\node_modules\base58-native
gyp ERR! node -v v0.10.33
 v1.0.1! |node-gyp -v
gyp ERR! not ok
-

> microtime@0.6.0 install C:\insight-api\node_modules\microtime
> node-gyp rebuild

\
C:\insight-api\node_modules\microtime>node "C:\Program Files\nodejs\node_modules
\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
|

**Comment by jl2035** [comment]
lool.. you really want to run this on wondoz :)

**Comment by braydonf** [comment]
Windows isn't supported, can be resolved with: https://github.com/bitpay/bitcore-node/issues/271
