### ISSUE TITLE
insight.bitpay.com: Errors when connecting to websocket

### ISSUE THREAD

**Issue by jonwaller** [bitpay/insight-api#273]
Code snippet 1:

```
    var wsUri = "wss://insight.bitpay.com";
    var websocket=new WebSocket(wsUri);

    websocket.onMessage=function(evt){ console.log(message); }
    websocket.onError=function(evt){ console.log(evt); }
```

Error from code snippet 1:

```
WebSocket connection to 'wss://insight.bitpay.com/' failed: Error during WebSocket handshake: Unexpected response code: 200
```

Code snippet 2:

```
<script src="https://insight.bitpay.com/socket.io/socket.io.js"></script>
<script>
var eventToListenTo = 'tx';
var room = 'inv';
var socket = io("https://insight.bitpay.com/");
socket.on('connect', function() {
  socket.emit('subscribe', room);
});
socket.on("tx", function(data) {
  console.log(data);
});
</script>
```

Error from code snippet 2:

```
WebSocket connection to 'wss://insight.bitpay.com/socket.io/?EIO=2&transport=websocket&sid=45phrp2GEjPdrlOgABKU' failed: Error during WebSocket handshake: Unexpected response code: 400
```

Code snippet 1 fails completely, but snippet 2 throws the error and then successfully receives transaction data. I believe this is different behaviour to a week ago, but cannot verify this.

I have also tried using this tool:
http://www.websocket.org/echo.html

And it also fails to connect to wss://insight.bitpay.com. (Complete failure - no transaction data)

**Comment by justinvforvendetta** [comment]
hey guys, i have a javascript, that was previous using ws://server.com/inv as its websocket. i just finished building an insight explorer, and was wondering what the syntax would be. i have tried ws://mynewinsight.com/inv, ws://mynewinsight.com/socket.io, ws://mynewinsight.com/socket.io/1, etc. 

im so confused, a bit of help?
