### ISSUE TITLE
Failed at the insight-bitcore@0.2.5 start script.

### ISSUE THREAD

**Issue by davithuroyan** [bitpay/insight-api#274]
Hi I get an error Like this can you help me ?

npm ERR! insight-bitcore@0.2.5 start: `INSIGHT_PUBLIC_PATH=public node node_modules/.bin/insight-bitcore-api`
npm ERR! Exit status 135
npm ERR!
npm ERR! Failed at the insight-bitcore@0.2.5 start script.
npm ERR! This is most likely a problem with the insight-bitcore package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     INSIGHT_PUBLIC_PATH=public node node_modules/.bin/insight-bitcore-api
npm ERR! You can get their info via:
npm ERR!     npm owner ls insight-bitcore
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.2.0-67-virtual
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! cwd /var/www/insight
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! nospc ENOSPC, write
npm ERR! nospc This is most likely not a problem with npm itself
npm ERR! nospc and is related to insufficient space on your system.

npm ERR! System Linux 3.2.0-67-virtual
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! cwd /var/www/insight
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ENOSPC
npm ERR! errno 54
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/insight/npm-debug.log
npm ERR! not ok code 0

**Comment by braydonf** [comment]
Please try https://bitcore.io/guides/full-node as this issue is now outdated.
