### ISSUE TITLE
Cant connect to paycoind

### ISSUE THREAD

**Issue by ChristianGrieger** [bitpay/insight-api#284]
info: insight server listening on port 8000 in development mode
POST / 404 15ms - 44b
error: Not found
{ '0': 'connecting to 127.0.0.1:3020' }
{ '0': 'connection refused for 127.0.0.1:3020' }
{ '0': 'unkown error with peer 127.0.0.1:3020 (disconnecting): Error: connect ECONNREFUSED' }
{ '0': 'disconnected from peer 127.0.0.1:3020' }

--

i really hope you have a solution i try this now for hours :( also followed the api setup

**Comment by afk11** [comment]
You likely need to update Bitcore, and Insight, to use your network/address bytes, genesis block, and other hardcoded constants.

**Comment by ChristianGrieger** [comment]
So i asked many people to help me to get it to work to set the genesis block and so on but no one was able to do it. So there is another timestamp format used for paycoin and we even was not able to find the magic number we needed.. Sorry i do not understand much of this and really would need someone to help to get this work. Maybe you are able to do that ?

**Comment by braydonf** [comment]
Outdated
