### ISSUE TITLE
Graceful termination & restart

### ISSUE THREAD

**Issue by kentdome** [bitpay/insight-api#285]
What’s the best way, convention to gracefully restart the node insight.js server?

**Comment by liferealized** [comment]
I'm using forever with startup in ubuntu. The script should be able to be ported to init.d for other debian distros.

https://gist.github.com/liferealized/d5f7fa1e01bfc926c3f4

https://github.com/foreverjs/forever

**Comment by martindale** [comment]
Additionally, I've had good luck with [pm2](https://github.com/Unitech/pm2), which has replaced `forever` in many contexts for me.
