### ISSUE TITLE
API should allow you to retrieve blocks by height as well as hash

### ISSUE THREAD

**Issue by rktoomey** [bitpay/insight-api#295]
Most of the other blockchain explorer APIs let you do this.

```
  /api/block/[:hash]
  /api/block/00000000a967199a2fad0877433c93df785a8d8ce062e5f9b451cd1397bdbf62

  /api/block/[:height]
  /api/block/344070
```

or `/api/block?height=344070` or whatever syntax you prefer, but please add it.

**Comment by rktoomey** [comment]
Also the API documentation in the README fails to mention the existence of `/api/block-index/[:height]` which while not as good as being able to just get the block by height, offers the possibility of something better than brute force recursion via `previousblockhash`

**Comment by lirazsiri** [comment]
This doesn't seem to be documented either but the default Insight frontend has a route on /block-index that uses the /api/block-index/ call to redirect to the right blockhash.

**Comment by lirazsiri** [comment]
FWIW regarding the /api documentation, on the blockexplorer frontend fork I added an /api page that provides an API reference and documented /api/block-index. Hope they merge that back in.

**Comment by braydonf** [comment]
Yep, `/api/block-index/[:height]` works for getting the hash.
