### ISSUE TITLE
Unhandled error in events.js

### ISSUE THREAD

**Issue by lekanovic** [bitpay/insight-api#298]
I have installed bitcoind(v0.9.4) and synced the whole block chain. The bitcoind is running in the background as a daemon and can be  acceessed using the bitcoin-cli command.

I have now for several days tried to use the insight-api backend but I keep getting the same error. Each time I get the error I reset the database accordingly to the instructions "utils/sync.js -D". And restart the init process. It takes very long time to run the command "node insight.js" around 15-20 hours. And during this time I get a couple of  times the error "{ '0': [Error: Could not connect to bitcoin via RPC: connect EMFILE] }". But I am able to get around it by restarting the insight.js.

So the real problem that I cannot bypass is when the insight console progress is getting closer to [~95%] then I get this error.

info: status: [96.923%]
error: IO error: /home/user/.insight/txs/478569.log: Too many open files
[historic_sync] ABORTED with error: IO error: /home/user/.insight/txs/478569.log: Too many open files

When I try to rerun the insight I get this error:

$ node insight.js

    ____           _       __    __     ___          _ 
   /  _/___  _____(_)___ _/ /_  / /_   /   |  ____  (_)
   / // __ \/ ___/ / __ `/ __ \/ __/  / /| | / __ \/ / 
 _/ // / / (__  ) / /_/ / / / / /_   / ___ |/ /_/ / /  
/___/_/ /_/____/_/\__, /_/ /_/\__/  /_/  |_/ .___/_/   
                 /____/                   /_/           

						v0.2.12

info: insight server listening on port 3000 in development mode
{ '0': 'connecting to 127.0.0.1:8333' }

events.js:72
        throw er; // Unhandled 'error' event
              ^
OpenError: Corruption: 2 missing files; e.g.: /home/user/.insight/txs/463401.ldb
    at /home/user/projects/insight-api/node_modules/levelup/lib/levelup.js:118:34

This is 100% reproduceble for me and I have restarted to process 3 times with same result. Have anyone seen this error or do you know how to solve it?

Thanks!

**Comment by maraoz** [comment]
Sounds like this could be a hidden bug only happening after the amount of blocks is above a certain number (thus making the amount of block files big enough to trigger this bug).
I'll try syncing an insight instance from scratch and report back. Thanks for reporting!
JIC: are you on livenet or testnet?

**Comment by lekanovic** [comment]
I have redone the whole procedure on a another computer and I got it to
work without any problem. So I think the problem can be related to if you
do not finish the whole sync in one call. On my other desktop my sync was
aborted several times due to loosing communication with bitcoind. I have
another question how long time does the sync normally take? For me to do
the full sync it takes around 20 hours which seems to be a very long time.
I know the blockchain is 35GB but still.

I am running on livenet.







Radovan Lekanovic

Senior Software Engineer
m:+17602747148 | e:lekanovic@gmail.com

**Comment by prabjot678** [comment]
I am also dealing with same error,but i am trying resync using sudo INSIGHT_NETWORK=livenet util/sync.js  -R ,but same error is occuring 

[options] { forceStartFile: undefined,
  forceRPC: true,
  startAt: undefined,
  stopAt: undefined }

events.js:72
        throw er; // Unhandled 'error' event
              ^
OpenError: Corruption: 67 missing files; e.g.: /home/oodles4/.insight/blocks/001369.ldb
    at /home/oodles4/Documents/production/insight-api/node_modules/levelup/lib/levelup.js:118:34
 

How to resolve it ?

**Comment by braydonf** [comment]
Outdated now. Please try running with latest version (leveldb is used in bitcoind directly).
