### ISSUE TITLE
Block Reward on block Summary

### ISSUE THREAD

**Issue by Cryptcollector** [bitpay/insight-api#303]
I was wondering where the Block Reward is gathered from, is it from the client itself or is there a setting somewhere to set this manually?

I am creating an BlockExplorer for an Alt coin and for some reason it it giving a result of 50 BTC instead of the actual coin Block Reward and designation of 100 ISO....

Could this be a problem with the coin client itself not being writen right?

**Comment by ChristianGrieger** [comment]
Same problem for me! Would love to know how to fix that :)

**Comment by braydonf** [comment]
The block reward is coming from https://github.com/bitpay/insight-api/blob/master/lib/blocks.js#L332-344 and is specific for bitcoin.
