### ISSUE TITLE
Configure Insight-api to show unconfirmed transactions

### ISSUE THREAD

**Issue by prabjot678** [bitpay/insight-api#307]
I am new to Insight-api. I want to show latest transaction (Unconfirmed transactions) similar to blockchain.info.But could not find any helping doc for that. 

Is it supported by Insight-Api.

If it is supported, how I can configure it. at both side i.e. client(UI)  and server.

Thanks

**Comment by fanatid** [comment]
What about [example](https://github.com/bitpay/insight-api#example-usage) in readme?
You can run next code in node.js and see new transactions for livenet:
```js
var io = require('socket.io-client')
var socket = io('https://insight.bitpay.com/')
socket.on('connect', function () {
  socket.emit('subscribe', 'inv')
})
socket.on('tx', function (data) {
  console.log('New transaction: ' + data.txid)
})
```

**Comment by prabjot678** [comment]
Thanku, it is working fine,but it seems to be slow as compared to insight.bitpay.com , why it is ,we are using testnet or another issue ?

**Comment by fanatid** [comment]
If you want using testnet, you must connect to `https://test-insight.bitpay.com/`
When I'm running example, I see same transactions that insight.bitpay.com showed...
Also you can read code of [insight front-end](https://github.com/bitpay/insight/blob/master/public/src/js/controllers/index.js#L21) and see that it does same things, that the example.

**Comment by prabjot678** [comment]
@fanatid  thanku very much, working fine as well as test-insight.bitpay.com.
