### ISSUE TITLE
Address Pagination?

### ISSUE THREAD

**Issue by alexanderkent** [bitpay/insight-api#309]
Trying a huge address such as 1dice9wcMu5hLF4g81u8nioL5mmSHTApw appears to kill the api. 

     /api/addr/1dice8EMZmqKvrGE4Qc9bUFf9PX3xaYDp?noTxList=1 works (~5 seconds) 

Is there a way we could paginate through say the first 0-20 transactions for 1dice8EMZmqKvrGE4Qc9bUFf9PX3xaYDp?

**Comment by matiu** [comment]
Insight was not designed to handle these popular addresses. I dont think it
will work unless a major change is done that the backend.



On Wed, Apr 29, 2015 at 1:48 AM, Alexander Kent <notifications@github.com>
wrote:

> Trying a huge address such as 1dice9wcMu5hLF4g81u8nioL5mmSHTApw appears to
> kill the api.
>
> /api/addr/1dice8EMZmqKvrGE4Qc9bUFf9PX3xaYDp?noTxList=1 works (~5 seconds)
> -- is there a way we could paginate through say the first 0-20 transactions
> for 1dice8EMZmqKvrGE4Qc9bUFf9PX3xaYDp?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/insight-api/issues/309>.
>



-- 
BitPay.com

**Comment by jl2035** [comment]
Isn't this like a huge problem?

**Comment by matiu** [comment]
> Isn't this like a huge problem?
>

Depending the use case.  In many occasions address are not reused and TX by
address are keep under ~ <10,000 entries.

**Comment by afk11** [comment]
10,000 sounds like a random figure, but it pales against the present number of transactions at least. It's small enough to be prohibitive in what I'm doing - I have 160,000 transactions on one address (#323). I don't see why the number of results should affect the results...

**Comment by jl2035** [comment]
So there's really no way to limit those requests and have some kind of pagination?

This is the first time I hear that something is not possible in programming.. :(

**Comment by matiu** [comment]
> So there's really no way to limit those requests and have some kind of pagination?

To calculate the balance, you need to process all txs.

> This is the first time I hear that something is not possible in programming.. :(

Where you heard that?

**Comment by jl2035** [comment]
There must be a way. How does blockchain.info do this instantly?
https://blockchain.info/address/1dice8EMZmqKvrGE4Qc9bUFf9PX3xaYDp

I believe their api is not open source, but I guess they could tell us how they do this in theory.

**Comment by wargo32** [comment]
They probably use regular database, have good servers and cache some informations.

If you need to list all transactions with their data and **paginate** them, use `/api/txs?address=ADDRESS&pageNum=X`

**Comment by afk11** [comment]
@matiu Do you mean the current, 'up to date' balance on the paginated results set? Or which?

I suppose you maintain a second index of Outpoint's to balances. Blockchain.info aren't processing every tx on an API call - pre-processing and storing some small redundant data is probably the way forward here.

**Comment by jl2035** [comment]
On my end I could fix this with caching. Do we know a number of txs when the api crashes? Or does this depend on the hardware?

**Comment by matiu** [comment]
> @matiu Do you mean the current, 'up to date' balance on the paginated results set? Or which?

the balance of an address 

> I suppose you maintain a second index of Outpoint's to balances. Blockchain.info aren't processing
> every tx on an API call - pre-processing and storing some small redundant data is probably the way
> forward here.

I guess there are many ways to solve that problem, as I mention before, this use case in particular is not really important for us, but we will have to accept a pull request that fix it.

**Comment by wargo32** [comment]
<code>/api/addr/ADDRESS?noTxList=1</code>

**Comment by afk11** [comment]
@wargo32 
https://test-insight.bitpay.com/api/addr/mvoh3Jwirz6YLdSdpp1558uHWdJ9Qpijjg?noTxList=1 still crashes. 
https://test-insight.bitpay.com/address/mvoh3Jwirz6YLdSdpp1558uHWdJ9Qpijjg

@jl2035 That seems to be unknown..

@matiu What use case are you talking about though? Surely trying to use the insight frontend to view an address is a reasonable use case? 

The subject of this PR has just been getting the transactions, not the total balance.

**Comment by jl2035** [comment]
To answer my own question.. it's not just how many txs, but also how big they are.

**Comment by braydonf** [comment]
Once cached, pagination should work now.
