### ISSUE TITLE
How to do reindexing insight db

### ISSUE THREAD

**Issue by prabjot678** [bitpay/insight-api#312]
Is there any way to reindexing  db instead of deleting it every time and resync again like this 

sudo INSIGHT_NETWORK=livenet util/sync.js  -D 

sudo INSIGHT_NETWORK=livenet util/sync.js  -R

it takes more time,every block and transaction checks again and again

**Comment by wargo32** [comment]
Add --start [blockhash] parameter.
More: https://github.com/bitpay/insight-api/blob/master/util/sync.js
