### ISSUE TITLE
Block transactions performance issue and Blocks are missing 

### ISSUE THREAD

**Issue by prabjot678** [bitpay/insight-api#314]
I am facing performance issue while fetching transactions by block hash. sometimes response faster but sometimes timeout issue or not found ,but i am searching it for latest block. Some times,if transaction array length arround 80,then api takes 1 min. but if i am checking it on insight with same block hash,there is searching 20 times faster then mine. i am working on testnet. so guys help me, if am doing something wrong ? 

The api is 
/api/txs?block=000000000000000013ebb8ca08cb76b0c79c85550971874ffb78e954e226400b&pageNum=0

my db is 100% sync 
and  my blocks are missing, my block height is 394383

block list coming on home page like this .. 394383,394374,69,68 etc
 what's wrong there ? 

Thanks

**Comment by jl2035** [comment]
maybe put "txindex=1" in bitcoin.conf and then download the blockchain again with reindex

**Comment by prabjot678** [comment]
@jl2035 could you tell me please how to reindex ?

**Comment by jl2035** [comment]
I've done this months ago, so I might not be 100% correct. 

you run bitcoind with -reindex option. you might even want to delete your blocks files before that. a few days is needed for this process.

**Comment by prabjot678** [comment]
@jl2035  okay.. thanks
