### ISSUE TITLE
Bug: API says output is spent when it really isn't

### ISSUE THREAD

**Issue by swiftbit** [bitpay/insight-api#315]
See the utxo for 1A2FJLox8Xb8uf2yh1C8CQLkGQ27kCSbdH

https://insight.bitpay.com/api/addrs/1A2FJLox8Xb8uf2yh1C8CQLkGQ27kCSbdH/utxo
vs
https://blockchain.info/unspent?active=1A2FJLox8Xb8uf2yh1C8CQLkGQ27kCSbdH
and
http://btc.blockr.io/api/v1/address/unspent/1A2FJLox8Xb8uf2yh1C8CQLkGQ27kCSbdH

**Comment by braydonf** [comment]
These are all showing as spent now.
