### ISSUE TITLE
Confusion in TX object received from Web Socket.

### ISSUE THREAD

**Issue by emrekenci** [bitpay/insight-api#320]
The data I receive when I subscribe to the "tx" event on the room "inv" is formatted as below:

{
   "txid": "d2b09ad23be1d74d3e6b37066d05438d567b929ac3d325a5a375ccc7a84035b0",
  "valueOut": 0.08435091,
  "vout": [
    {
      "1MPxhNkSzeTNTHSZAibMaS8HS1esmUL1ne": 55091
    },
    {
      "1LRNfWdVpBmVFfFhVbCEMMZAXKX35fmhfx": 8380000
    }
  ]
}

The docs on the homepage say "Data will be a app/models/Transaction object. Sample output:" 

I have one issue and one question:

1) There is no Transaction object under app/models. There are two files there and neither defines a Transaction object

2) Is it not possible to get the full transaction details for all unconfirmed transactions using the web socket Insight API? Specifically, I need the inputs too.

**Comment by jl2035** [comment]
When you receive the tx event, you can query the api and get the full tx data. I guess socket api is not meant to transfer big messages.
