### ISSUE TITLE
Insight API time's out when the address has many transactions

### ISSUE THREAD

**Issue by afk11** [bitpay/insight-api#323]
https://test-insight.bitpay.com/address/mvoh3Jwirz6YLdSdpp1558uHWdJ9Qpijjg

The API times out after 40+ seconds on this request, and seems to trigger a redirect to the homepage on the insight UI (the UI did this as you'll see on the above url, and directly calling the API using curl also returned HTML)

The address has about 160k transactions, but it should still work ;)

**Comment by jl2035** [comment]
Yes this is very frustrating for me too. And it has been discussed already: https://github.com/bitpay/insight-api/issues/309

Can't you guys do something about it? Or at least give us some time frame... when can we expect this to be fixed?

**Comment by matiu** [comment]
dup https://github.com/bitpay/insight-api/issues/309

@jl2035 see discussion at #309.
