### ISSUE TITLE
magic number mismatch, magic is correct though

### ISSUE THREAD

**Issue by doged** [bitpay/insight-api#326]
Deleting Sync DB...
info: Bitcoin Core version  v1.2.0.0-beta
info: Using RPC sync
[options] { forceStartFile: undefined,
  forceRPC: undefined,
  startAt: undefined,
  stopAt: undefined }
info: Seeking file to:00000fc63692467faeb20cdb3b53200dc601d75bdfa1001463304cc790d77278
        FOUND Starting Block!
info: Got 0 blocks in current DB, out of 189728 block at bitcoind
info: bitcoind dataDir configured...importing blocks from .dat files
info: First file index: 0
info: Starting from:  00000fc63692467faeb20cdb3b53200dc601d75bdfa1001463304cc790d77278
info: status: [0%]
Reading Blockfile /root/.DogeCoinDark/blk0001.dat [149 MB]
Moving forward to file:/root/.DogeCoinDark/blkindex.dat
Reading Blockfile /root/.DogeCoinDark/blkindex.dat [106 MB]

/root/insight-doged/node_modules/insight-bitcore-api/lib/BlockExtractor.js:102
      throw new Error('CRITICAL ERROR: Magic number mismatch: ' +
            ^
Error: CRITICAL ERROR: Magic number mismatch: 8c9d7a00!=f7a77eff
    at BlockExtractor._getMagic (/root/insight-doged/node_modules/insight-bitcore-api/lib/BlockExtractor.js:102:13)
    at BlockExtractor.getNextBlock (/root/insight-doged/node_modules/insight-bitcore-api/lib/BlockExtractor.js:120:17)
    at HistoricSync.getBlockFromFile (/root/insight-doged/node_modules/insight-bitcore-api/lib/HistoricSync.js:179:23)
    at /root/insight-doged/node_modules/insight-bitcore-api/lib/HistoricSync.js:443:14
    at Object.async.whilst (/root/insight-doged/node_modules/insight-bitcore-api/node_modules/async/lib/async.js:753:13)
    at /root/insight-doged/node_modules/insight-bitcore-api/node_modules/async/lib/async.js:757:23
    at Object._onImmediate (/root/insight-doged/node_modules/insight-bitcore-api/lib/HistoricSync.js:451:24)
    at processImmediate [as _immediateCallback] (timers.js:330:15)

----------------------------------------------------------------------------------------------

the f7a77eff is the correct magic number, from the coin source code. where is it pulling this 8c9d7a00 number from?  is there somewhere else, besides network.js that i need to modify the magic number?

**Comment by doged** [comment]
Error: CRITICAL ERROR: Magic number mismatch: e5a37f00!=f7a77eff
im still here no matter what i do. where is it getting e5a37f00 from ?

**Comment by doged** [comment]
i think it may be the script patch. do i add the patch, or replace the existing code with it?

**Comment by mmitech** [comment]
Hello ! 

how did you solve this ?

**Comment by doged** [comment]
@mmitech oh boy.. where do i begin?! first off, what algo are you working with, and is it PoS or PoW?

**Comment by mmitech** [comment]
it is scrypt-jane and it is a mix of POW and POS https://github.com/Leocoin-project/LEOcoin

**Comment by doged** [comment]
@mmitech https://github.com/Leocoin-project/LEOcoin/blob/949243c6e3db2fabf9c4338465bba55b89e32934/src/main.cpp#L3023

so your magic number is d9e6e7e5 =]

**Comment by mmitech** [comment]
@doged  yes that is my magic, but I get "throw new Error('CRITICAL ERROR: Magic number mismatch: '"  I can only sync if I force rpc by "util/sync.js -D -R" , but after a while one CPU core (one insight thread) goes to 100% and it stops responding requests.

**Comment by mmitech** [comment]
so how did you fix the Magic number mismatch ?

**Comment by doged** [comment]
@mmitech have you implemented pow/pos into the code yet? insight is made for PoW only at the moment because bitcoin.

**Comment by mmitech** [comment]
why didn't work for you? your coin is POW! can you tell me what did you change in the code exactly?

**Comment by doged** [comment]
@mmitech doged is PoW, but i built it from a PoS, but disabled the staking. the ntime is still sent in tx headers.. so i just had to add that n scrypt

**Comment by doged** [comment]
@mmitech that is done in bitcore though, not the insight-api

**Comment by mmitech** [comment]
@doged excellent! can you please refer me to the change you did and where did you change it exactly ?

**Comment by doged** [comment]
in lib/block.js and lib/transaction.js, if memory serves correct. just browse those and implement scrypt-jane instead of sha256

**Comment by mmitech** [comment]
@doged Thank you, I will look at it and let you know.

**Comment by mmitech** [comment]
@doged in lib/block.js I see the same code lines for scrypt (litesight) and sha256 (insight)
Block.prototype.calcHash = function calcHash() {
  var header = this.getHeader();

  return util.twoSha256(header);
};

I am totally lost here, can you at least paste the code you've changed here ?

**Comment by doged** [comment]
return util.scrypt(header);

same goes for transaction. and dont forget to include the scrypt-jane module!

**Comment by mmitech** [comment]
@doged can you please pastebin (or just paste it here) your scrypt module with the block and transaction changes you've made ? I am not fluent in javascript...

**Comment by cryptozeny** [comment]
@doged 

hi, i have a same issue. where is scrypt-jane module? where should i put it?
