### ISSUE TITLE
cant connect p2p

### ISSUE THREAD

**Issue by doged** [bitpay/insight-api#327]
starts up with:
INSIGHT_NETWORK=livenet BITCOIND_HOST="127.0.0.1"  BITCOIND_USER=rpcuser BITCOIND_PASS=rpcpassword INSIGHT_PUBL_PATH=public BITCOIND_P2P_PORT=8333 BITCOIND_PORT=8332 npm start

(i can connect thru telnet to 127.0.0.1 8333)

 # Configuration:
                Network: livenet        INSIGHT_NETWORK
                Database Path:  /root/.insight  INSIGHT_DB
                Safe Confirmations:  6  INSIGHT_SAFE_CONFIRMATIONS
                Ignore Cache:  no       INSIGHT_IGNORE_CACHE
 # Bicoind Connection configuration:
                RPC Username: dogedexplorer     BITCOIND_USER
                RPC Password: Yes(hidden)       BITCOIND_PASS
                RPC Protocol: http      BITCOIND_PROTO
                RPC Host: 127.0.0.1     BITCOIND_HOST
                RPC Port: 8332  BITCOIND_PORT
                P2P Port: undefined     BITCOIND_P2P_PORT  <- why undefined?!
                Data Dir: /root/.DogeCoinDark/  BITCOIND_DATADIR
info: starting...
insight server listening on port 3000 in development mode
info: Resuming sync from block: 0000000000356613026b451622a61365509fec4be9cf0023dccbb15d5e9b5fa5 #189824
info: Got 189824 blocks in current DB, out of 189825 block at bitcoind
info: syncing from RPC (slow)
info: Starting from:  0000000000356613026b451622a61365509fec4be9cf0023dccbb15d5e9b5fa5
info: status: [99.999%]
 REORG Triggered, tip mismatch
info: NEW TIP: 0000000000356613026b451622a61365509fec4be9cf0023dccbb15d5e9b5fa5 NEED REORG (old tip: 0000000000356613026b451622a61365509fec4be9cf0023dccbb15d5e9b5fa5 #189824)
info: # Reorg Case 1) OldNext: 0000000000356613026b451622a61365509fec4be9cf0023dccbb15d5e9b5fa5 NewHeight: 189824
info:   Unconfirming 3 Txs
Done Syncing { status: 'finished',
  blockChainHeight: 189825,
  syncPercentage: '100.000',
  height: 189825,
  syncTipHash: undefined,
  error: null,
  type: 'from RPC calls',
  startTs: 1435587974082,
  endTs: 1435587974108 }
info: status: [100%]
{ '0': 'connecting to 127.0.0.1:8333' }
{ '0': 'disconnected from peer 127.0.0.1:8333' } <- disconnects

at this point, site is online, but rpc sync'd only. 

website (missing 8333 after localhost for some reason) reads: 
Can't connect to dogecoindarkd to get live updates from the p2p network. (Tried connecting to dogecoindarkd at 127.0.0.1: and failed.)

i have put the proper version (60016) in, and all settings in configs are accurate as far as i can tell. 

any suggestions? willing to tip.

**Comment by doged** [comment]
here is the site online, if it helps. http://104.236.58.93:3000/blocks

if anyone knows where i should be looking to fix the p2p.. also, not sure why the port disappeared from the localhost in the error message.. hmmm

**Comment by doged** [comment]
well, the p2p port not showing up on the site warning was a type in PeerSync, but i fixed that. still same issue though.

**Comment by doged** [comment]
it still says "undefined" in the console startup.

**Comment by doged** [comment]
ok so i set it to keep trying to connect to the p2p, and suddenly this happened:

{ '0': 'connecting to 127.0.0.1:8333' }
{ '0': 'disconnected from peer 127.0.0.1:8333' }
{ '0': 'connecting to 127.0.0.1:8333' }
{ '0': 'disconnected from peer 127.0.0.1:8333' }
{ '0': 'connecting to 127.0.0.1:8333' }
[p2p_sync] Handle tx: ebbe0ff6b1428353ba22b144c8b3ec0c8ee76c616b9c3deabb81a7b0c4bcf143
[p2p_sync] Handle tx: ebbe0ff6b1428353ba22b144c8b3ec0c8ee76c616b9c3deabb81a7b0c4bcf143
[p2p_sync] Handle tx: ebbe0ff6b1428353ba22b144c8b3ec0c8ee76c616b9c3deabb81a7b0c4bcf143
[p2p_sync] Handle tx: ebbe0ff6b1428353ba22b144c8b3ec0c8ee76c616b9c3deabb81a7b0c4bcf143
[p2p_sync] Handle tx: ebbe0ff6b1428353ba22b144c8b3ec0c8ee76c616b9c3deabb81a7b0c4bcf143
[p2p_sync] Handle tx: ebbe0ff6b1428353ba22b144c8b3ec0c8ee76c616b9c3deabb81a7b0c4bcf143

**Comment by doged** [comment]
its *sort* of working almost, the website is now showing the new block without refresh, but its constantly scrolling.

**Comment by doged** [comment]
http://104.236.58.93:3000/blocks
showing list of recent blocks, but multiple entries for each

**Comment by doged** [comment]
it seems to be connecting to the p2p node now, but it took 3 tries when insight started up

**Comment by doged** [comment]
http://pastebin.com/ahaShQT8

the p2p connects now, but it takes several tries, then scrolls

**Comment by doged** [comment]
ah ok got it working. that was tough.

**Comment by strataghyst** [comment]
Hey got the same problem how did you fix this?
