### ISSUE TITLE
Error: Wont start to sync while status is starting

### ISSUE THREAD

**Issue by vdidonato** [bitpay/insight-api#328]
After a few days of successful usage these log messages appeared:

error: ## Wont start to sync while status is starting
info: Resuming sync from block: 000000000000000011ecad6cbf1585f6414fcc80f20f7fa544220c558e17ef15 #363011
info: Got 363011 blocks in current DB, out of 363015 block at bitcoind
info: syncing from RPC (slow)
info: Starting from:  000000000000000011ecad6cbf1585f6414fcc80f20f7fa544220c558e17ef15
info: status: [99.999%]
info: status: [99.999%]
info: NEW TIP: 000000000000000011ecad6cbf1585f6414fcc80f20f7fa544220c558e17ef15 NEED REORG (old tip: 000000000000000011ecad6cbf1585f6414fcc80f20f7fa544220c558e17ef15 #363011)
info: Reorg Case 1) OldNext: 000000000000000011ecad6cbf1585f6414fcc80f20f7fa544220c558e17ef15 NewHeight: 363011
info:   Unconfirming 2342 Txs
error: ## Wont start to sync while status is syncing
info: status: [99.999%]
info: status: [100%]

Now everything seems normal.....but: should I worry?
(I'm always syncing from RPC because I'm on bitcoind 0.10.something)

**Comment by posita** [comment]
I'm seeing these periodically as well. Is this some race condition somewhere that we should be worried about?

**Comment by braydonf** [comment]
Should no longer be an issue with 0.3.0
