### ISSUE TITLE
Storing a block should be atomic

### ISSUE THREAD

**Issue by jojva** [bitpay/insight-api#329]
The process of syncing, whether it is File Sync, RPC Sync or Peer Sync, adds a block to leveldb in several steps (several `db.put`). In the function `Sync.prototype.storeTipBlock()`, first a block is added with `bDb.add()`, then it is tagged as the tip with `bDb.setTip()`, and the previous block linked to it with `bDb.setNext()`. These operations are collectively not atomic.

What happens if I interrupt the daemon with Ctrl-C, and the syncing is somewhere between these operations? For example, the block has been added, the tip has been set, but its previous block (let's call it `Prev`) has not been linked to it with `bDb.setNext()`. If I restart, Insight will see the tip, start again from here and `Prev` will never have a next block, right?

Shouldn't these operations be batched into leveldb?

**Comment by jojva** [comment]
I can see how it works now. Syncing always begins with the tip block, so it is processed a second time (first before the previous sync was halted, then at the beginning of the next sync), which always triggers a reorg case 1°.
Isnt it a bit hacky though?

**Comment by braydonf** [comment]
Outdated
