### ISSUE TITLE
running with forever nodejs

### ISSUE THREAD

**Issue by doged** [bitpay/insight-api#331]
is there a way to get this running with forever? i use forever to keep most of my scripts running without having to use screen. whats the best way to get this to stay up without using screen? or can i use forever start insight.js?

**Comment by wargo32** [comment]
`INSIGHT_NETWORK='livenet' INSIGHT_PUBLIC_PATH="public" forever start node_modules/insight-bitcore-api/insight.js`

**Comment by doged** [comment]
thanks @wargo32, worked like a charm!

**Comment by martindale** [comment]
The same works for `pm2`, fwiw, which I've found a suitable replacement for `forever`!

**Comment by carnesen** [comment]
I'll get on that pm2 love train. I find it to be waaaay better than
forever. I use it to keep my Node.js daemons running as well as my bitcoind.
