### ISSUE TITLE
broadcast endpoint failure (code -3)

### ISSUE THREAD

**Issue by shayanb** [bitpay/insight-api#333]
When I try to broadcast a signed transaction with the broadcast endpoint on search.bitaccess.ca it fails with the following error:
```
Expected type str, got null (code -3)
```
even though the same signed transaction would work with blockr.io or chain.com broadcast api. I had almost the similar issue with bitcore.js and the issue is when the signed transaction was generated with another library (in this case pycoin) it was not able to decode the hex properly, bitcore issue was on unspent transactions from the hex, but in this case I'm not sure what the problem is.

I found that this error code might be related to this line: https://github.com/bitpay/insight-api/blob/9802d7e99249345cb88813b2f4f33921424ac86e/lib/Rpc.js#L108
```
    if (err && (err.code === -3 || err.code === -5))
      return cb(err);  // -3 = invalid address, -5 = malformed base64 / etc.
    if (err)
      return cb(self.errMsg(err));
```

also this is how I call the api:
```
    url = "https://search.bitaccess.ca/api/tx/send"
    data = json.dumps({"rawtx":signed_tx})
    try:
        request = urlfetch.fetch(url,
                            payload=data,
                            method=urlfetch.POST)
        result = request.content
        logging.info("insight raw response %s" %result)
```

**Comment by shayanb** [comment]
to make things simpler, this fails with the same error:
```
curl -d {"rawtx":"010000000134f36186dcac5544d9d7c0626fb84d87812d390247b60b0e88c5f44dd9cd2964000000006a47304402203a6d25738ada09fe106854bf23a7c0b935111387e8a7a1e42fb2c6f85c6b7a04022019d46c6365e4f59fd3eea24b510a90078d57572725b8c5d95ab3500578d36236012103fa19c70763f2acad82a59bb393966b223e6e038262032581b2c108b88f7557fdffffffff0239050000000000001976a914582038c31563e5a0c1e32b47ccc541b2c89e382188acc0e40200000000001976a914fafa2cc8d5a8963bbe960bfaa98658f27ac9ea0488ac00000000"} https://search.bitaccess.ca/api/tx/send
```
```
Expected type str, got null (code -3)
```

**Comment by matiu** [comment]
this is not related to insight, but `bitaccess.ca` installation.
