### ISSUE TITLE
broadcast endpoint failure (code -8)

### ISSUE THREAD

**Issue by shayanb** [bitpay/insight-api#334]
following to https://github.com/bitpay/insight-api/issues/333, I changed the server to both chain.localbitcoins.com and insight.bitpay.com, this would lead to the following error:

parameter must be hexadecimal string (not '') (code -8)
```
curl -d {"rawtx":"01000000014ff575611b31f87256842532a3c9c14ee8d3aa2e4faea3861be05641eb3b7e5d000000006a473044022034c133143433b2820da5ce7de3ce1b47f79095926631581338ade9e224514dbf0220119a7ecc4ee69cf8a68c1f34f9e10d07211aa40bcc8831325885bc0b3ada480d012103fa19c70763f2acad82a59bb393966b223e6e038262032581b2c108b88f7557fdffffffff0239050000000000001976a914582038c31563e5a0c1e32b47ccc541b2c89e382188ac53070200000000001976a914fafa2cc8d5a8963bbe960bfaa98658f27ac9ea0488ac00000000"} https://chain.localbitcoins.com/api/tx/send
parameter must be hexadecimal string (not '') (code -8)
```

**Comment by eljoncurry2** [comment]
I am having the exact issue.  I'm a bit stuck.

**Comment by Rav3nPL** [comment]
```parameter 1 must be hexadecimal string (not 'send') [Host: localhost:8332 User:insight Using password:yes]. Code:-8```

**Comment by braydonf** [comment]
This curl command should work:
`curl -H "Content-Type: application/json" -X POST -d '{"rawtx": "[hexstring]"}' https://test-insight.bitpay.com/api/tx/send`
