### ISSUE TITLE
Small nit pick issue INSIGHT_FORCE_RPC_SYNC

### ISSUE THREAD

**Issue by spinza** [bitpay/insight-api#337]
I had an install working with a new bitcoind that had the block path pointed to an invalid path.  In the past this effectively forced RPC only sync.

When I upgraded this no longer worked.  Took me some time to realise that I had to explicitly set  INSIGHT_FORCE_RPC_SYNC = 1 now also.  I saw the note on this and thought I had already been doing RPC sync and thus it didn't apply.  Turns out it has to have the option.  Setting option fixes it.

**Comment by braydonf** [comment]
No longer relevant with v0.3
