### ISSUE TITLE
Critical bug with API method /api/addrs/[:addrs]/txs

### ISSUE THREAD

**Issue by stequald** [bitpay/insight-api#343]
I’m not getting all the transactions that are associated with some addresses with the recent change to an API method (this method /api/addrs/[:addrs]/txs). For example 15PBbr23Jo3bVL9GuNaBRf1sc1SesBYWN4 and 1F8QVEZrj5j9xYv4CukaMpu4ytiSN7vKLy contain two transactions each, but I only get back 1 transaction for each. Examples below.

Incorrect:
https://insight.bitpay.com/api/addrs/15PBbr23Jo3bVL9GuNaBRf1sc1SesBYWN4/txs
https://insight.bitpay.com/api/addrs/1F8QVEZrj5j9xYv4CukaMpu4ytiSN7vKLy/txs
https://insight.bitpay.com/api/addrs/15PBbr23Jo3bVL9GuNaBRf1sc1SesBYWN4,1F8QVEZrj5j9xYv4CukaMpu4ytiSN7vKLy/txs

correct:
https://insight.bitpay.com/api/txs/?address=1F8QVEZrj5j9xYv4CukaMpu4ytiSN7vKLy
https://insight.bitpay.com/api/txs/?address=15PBbr23Jo3bVL9GuNaBRf1sc1SesBYWN4

**Comment by matiu** [comment]
thanks for the report.

This is because insight-api version 0.2.17 has a bug at the /api/txs endpoind. it is fixed at 0.2.18. We will deploy that in insight.bitpay.com soon.

**Comment by matiu** [comment]
ok, it is upgraded. Thanks again for the report:
https://insight.bitpay.com/api/addrs/15PBbr23Jo3bVL9GuNaBRf1sc1SesBYWN4/txs
