### ISSUE TITLE
Getting `ABORTED with error: Could not connect to bitcoin via RPC: connect EADDRNOTAVAIL` when syncing mainnet

### ISSUE THREAD

**Issue by posita** [bitpay/insight-api#345]
I'm receiving these when I get to about 5% when syncing mainnet:

```
{ '0': [Error: Could not connect to bitcoin via RPC: connect EADDRNOTAVAIL] }
error: Could not connect to bitcoin via RPC: connect EADDRNOTAVAIL
[historic_sync] ABORTED with error: Could not connect to bitcoin via RPC: connect EADDRNOTAVAIL
```

`bitcoind` is running on the same machine and insight connects to it at first. `bitcoind` remains running after insight fails. This *might* be okay, if insight didn't also require a complete resync after attempting to restart. :angry:

**Comment by braydonf** [comment]
Connection is no longer using RPC.

**Comment by posita** [comment]
@braydonf, is that true even where `bitcoind` >= 10.0.0? Or is this now a function of migrating the underlying implementation to bitcore-node? My apologies if I have not kept up on this....

**Comment by braydonf** [comment]
bitcoind is now compiled in at version 0.11.1, more details: https://github.com/bitpay/bitcore-node

**Comment by posita** [comment]
Thanks @braydonf! :+1:
