### ISSUE TITLE
Why doesn't insight attempt to re-establish severed connections to bitcoind peer ?

### ISSUE THREAD

**Issue by lirazsiri** [bitpay/insight-api#349]
If bitcoind is restarted, Insight doesn't attempt to re-establish Peer connection. Insight itself has to be restarted for the connection to be re-established, and you have to notice that's happened first (e.g., by polling /api/peer from a monitoring script and checking for connected:false).

Is there a good reason we don't create an interval that tries to re-establish the connection in lib/PeerSync.prototype.run for the peerman 'netDisconnected' event? I'm new to the codebase so excuse me if there's something glaringly obvious I'm missing.

**Comment by lirazsiri** [comment]
Here's a little script I wrote to work around this problem:
```bash
#!/bin/bash

if [ -z "$1" ]; then
        echo "usage: $0 testnet | livenet"
        exit 1
fi

mode=$1
if [ "$mode" != "testnet" ] && [ "$mode" != "livenet" ]; then
        echo "no such mode '$mode'"
        exit 1
fi

if [ "$mode" = "testnet" ]; then
        bitcoin_conf="/etc/bitcoin/bitcoind-testnet.conf"
        url="http://testnet.blockexplorer.com"
else
        bitcoin_conf="/etc/bitcoin/bitcoind.conf"
        url="http://blockexplorer.com"
fi
pm2_service="insight-$mode"

function insight_disconnected() {
        url="$1"
        [ "$(curl -s $url/api/peer | jq .connected)" = "false" ]
        return $?
}

function insight_online() {
        pm2 list | grep $pm2_service | grep online > /dev/null 
        return $?
}

function pm2_restart() {
        service="$1"
        echo -n "restarting $1: "
        pm2 restart --silent --no-color $service
}

function wait_until_ok() {
        command=$1
        while true; do
                $command > /dev/null && break
                sleep 1
        done
}

if insight_online && insight_disconnected $url; then
        wait_until_ok "bitcoin-cli -conf=$bitcoin_conf getinfo"
        pm2_restart $pm2_service
fi

exit 0
```

**Comment by zekylaf** [comment]
Hi, I am having the same problem with Insight (and others too) and I want to know where I can place this script to solve the problem that you describe.

Thanks in advance

**Comment by lirazsiri** [comment]
You'll need to run it as part of a cron job.

**Comment by zekylaf** [comment]
I will try it, thanks!

**Comment by braydonf** [comment]
Establishing connection should no longer be necessary.
