### ISSUE TITLE
403 Error response when requesting Total Received on single address

### ISSUE THREAD

**Issue by Jacobbubble** [bitpay/insight-api#354]
About 1 out of 20 times, I get the error: "No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 403." when requesting total received on an address.

GET https://insight.bitpay.com/api/addr/1EgznAKomxXKWaAnMg3fi5bZAJD1w7Srzu/totalReceived XMLHttpRequest cannot load https://insight.bitpay.com/api/addr/1EgznAKomxXKWaAnMg3fi5bZAJD1w7Srzu/totalReceived. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 403.

**Comment by braydonf** [comment]
Let us know if there are still any issues.
