### ISSUE TITLE
ERROR  code=-28, message=Activating best chain...

### ISSUE THREAD

**Issue by prabjot678** [bitpay/insight-api#369]
When i am trying to start insight i am getting error "ERROR  code=-28, message=Activating best chain..." . I saw this error first time,please help me how to reslove this. 

Full stack trace of error:

  ____           _       __    __     ___          _ 
   /  _/___  _____(_)___ _/ /_  / /_   /   |  ____  (_)
   / // __ \/ ___/ / __ `/ __ \/ __/  / /| | / __ \/ / 
 _/ // / / (__  ) / /_/ / / / / /_   / ___ |/ /_/ / /  
/___/_/ /_/____/_/\__, /_/ /_/\__/  /_/  |_/ .___/_/   
                 /____/                   /_/           

						v0.2.12

connection
info: insight server listening on port 3000 in development mode
error: ERROR  code=-28, message=Activating best chain...

Thanks in advance

**Comment by braydonf** [comment]
No longer relevant with v0.3.0
