### ISSUE TITLE
"bits" from RPC != "bits" from BlockExtractor

### ISSUE THREAD

**Issue by rubensayshi** [bitpay/insight-api#39]
I think this is an inconsistency that could (should?) be fixed, or at least I'd like to see it fixed.  
The problem is, I can't wrap my head around this, so I'm also a bit curious ;-)

with `getBlockFromRPC` the "bits" is "1900b3aa".  
with `getBlockFromFile` the "bits" is "419476394".  

the bitcore `util.calcDifficulty(419476394)` results in the proper difficulty ...  
I got as far as to realise that "1900b3aa" is hex for "419476394" and that if I do `parseInt("1900b3aa", 16)` I will get "419476394", which will thus result in the proper difficulty ...

but I can't think of a way to handle these 2 different values in the code when I switch between `getBlockFromRPC` and `getBlockFromFile`...  
I think these 2 should be consistent and I guess the "bits" returned from `getBlockFromFile` should be hex instead of an int right? 

changing `Block.parse` in bitcore to `this.bits = parser.buffer(4);` instead of `this.bits = parser.word32le();` turns the bits into the hex, but breaking the API in bitcore would suck so it would at this point be better to convert the int back to hex in `getBlockFromRPC` I guess ...

Also, that still doesn't allow you to convert hex -> difficulty properly with the `bitcore.util.util` ...

**Comment by braydonf** [comment]
I think this is outdated now, and not an issue anymore.
