### ISSUE TITLE
Stuck after 4 months at block379186

### ISSUE THREAD

**Issue by vdidonato** [bitpay/insight-api#407]
Hey guys. Today my inshight-api got stuck after 4 months of really good performances...
When asking /api/sync it says:

{"status":"syncing","blockChainHeight":379195,"syncPercentage":"99.998","height":379186,"error":null,"type":"from RPC calls","startTs":1445012738290,"endTs":null}
It seems stuck at 379186...and now when I ask for any information it takes ages to answer (it seems busy doing something else).

What am I supposed to do? Can I fix it somehow? Should I resync? Thanks

**Comment by braydonf** [comment]
No longer relevant with v0.3, since syncing isn't using RPC.
