### ISSUE TITLE
Insight API claims block in not on main chain / orphaned, this is not true

### ISSUE THREAD

**Issue by shachart** [bitpay/insight-api#41]
Block #292263
Hash: 0000000000000000eb9fc4859928e6205df95a78f8d9ccaa1efad0f40b5c3cf1

Can anyone reproduce? (I am re-building my local Core database AND will re-sync insight-api after that to confirm/reject bit rot / data issues, but this will take ~2 days)

using insight-api HEAD (08e125f0b2a77b58d39cba048e11131b00535746) and Bitcoin Core 0.9.1 as RPC server.

**Comment by braydonf** [comment]
No longer relevant with v0.3.0
