### ISSUE TITLE
Cannot GET /insight

### ISSUE THREAD

**Issue by zekylaf** [bitpay/insight-api#411]
Hi, when I go to http://localhost:3001/insight I get the message: "Cannot GET /insight"

What I can do? Thanks

Ps: Actually, Bitcoin Height: 1072 Percentage: 0.0005338747287169099

**Comment by braydonf** [comment]
The URL for the api is at /insight-api/

**Comment by zekylaf** [comment]
Thanks braydonf. I get the same if I go to this URL. "Cannot GET /insight-api/"

What I can do?

**Comment by zekylaf** [comment]
I could not find a solution yet. I found reading on internet that this error is related to nodejs.
@braydonf  do you know what is happening?

**Comment by braydonf** [comment]
The docs may need to be updated, but it sounds like insight-ui isn't installed. Try using "install" instead if "add".

**Comment by zekylaf** [comment]
I have reinstalled the os, try making changes in all the files of bitcore, and a lot of thing. Nothing works, but I try with "install" and suddenly, it starts working.
I am using Ubuntu 14.04.

Thanks a lot!

**Comment by zekylaf** [comment]
@braydonf: hi, I was trying to use the insight api since your last answer, but I can't yet.

I use "install" to install "insight-api" and "insight-ui" just like you told me. 
Now, my "bitcore-node.json" file says:

{
  "datadir": "./data",
  "network": "livenet",
  "port": 3001,
  "services": [
    "address",
    "bitcoind",
    "db",
    "insight-api",
    "insight-ui",
    "web"
  ]
}

If I go to http://<insight-server>:3001/insight, it open the "Insight Web Page" correctly,  but if I go to http://<insight-server>:3001/insight-api, it says "Cannot GET /insight-api".

When I installed the "insight-api", server said: 

insight-api@0.3.0 node_modules/insight-api
├── bitcore-message@1.0.2
├── async@1.5.0
├── lodash@2.4.2
└── request@2.65.0 (aws-sign2@0.6.0, forever-agent@0.6.1, caseless@0.11.0, stringstream@0.0.5, tunnel-agent@0.4.1, oauth-sign@0.8.0, form-data@1.0.0-rc3, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, node-uuid@1.4.3, qs@5.2.0, combined-stream@1.0.5, tough-cookie@2.2.0, mime-types@2.1.7, http-signature@0.11.0, bl@1.0.0, hawk@3.1.0, har-validator@2.0.2)
Successfully added services(s): insight-api

Can you help me please? Maybe I'm doing something wrong

Thanks in advance!

**Comment by braydonf** [comment]
I don't think there is a route setup for the base path, however `/insight-api/block/<blockHash>` should work.

**Comment by zekylaf** [comment]
Thanks for answer @braydonf. I try using "/insight-api/block/<blockHash>" and it works fine. I don't understand what is the "route setup for the base path". Where I can setup this? 

I imagine that is a file where I tell the system that when there is an incoming request for "/insight-api/api", it must response with "/api" or something like that.

**Comment by braydonf** [comment]
The routes are defined here: https://github.com/bitpay/insight-api/blob/master/lib/index.js

We probably should add one that says "It works!" for "/insight-api/" or something similar.

**Comment by zekylaf** [comment]
@braydonf  ok, thanks a lot. Now I understand. Thanks for help me.

**Comment by awsashish** [comment]
I have fixed that error to adding the ("insight-api", "insight-ui") in "bitcore-node.json" file and before that running the daemon again I have run the "npm install insight-api insight-ui"....

I got this working, i just want to share my tweak so no one stuck and killed the lot of time.
