### ISSUE TITLE
Block websocket data only includes blockhash

### ISSUE THREAD

**Issue by Tectract** [bitpay/insight-api#414]
The blocks websocket does not appear to be returning full block data object, only the block hash string. This is testing against https://insight.bitpay.com. Also I noticed in the code it looks like the transactions data is being thinned out and only tx hashes are being included there in the "transformed" block object. It would be really better for my purposes if the full tx data was included with the blocks. Or if the block data was returned at all...

**Comment by Tectract** [comment]
I may end up being able to contribute back onto the insight repos to fix these issues up that I'm submitting. It may take a while though.

**Comment by braydonf** [comment]
Querying the full block data after receiving the event, I believe to be the expectation here.
