### ISSUE TITLE
Watch address feature

### ISSUE THREAD

**Issue by nbabenko** [bitpay/insight-api#420]
Hi,

We need to subscribe to a list of addresses and receive callback notifications when there is incoming or outgoing transactions on this address. 

Proposed spec:
POST method: /insight-api/addrs/subscribe
POST params:
callback_link: "http://mywebsite.com/callback_link"
addrs: 2NF2baYuJAkCKo5onjUKEPdARQkZ6SYyKd5,2NAre8sX2povnjy4aeiHKeEh97Qhn97tB1f

Callback:
POST method: http://mywebsite.com/callback_link
POST params: 
address: 2NF2baYuJAkCKo5onjUKEPdARQkZ6SYyKd5
block: 382195
transactions: 5bf638fac0285221fe5a68504d9f2f9d6aacf750744553f4b4e4d6a984019558, ac088c8a95bea0430332857888c26b06e638324f5bebc6765c8deeba54627aa5

DELETE method: /insight-api/addrs/unsubscribe
POST params:
callback_link: "http://mywebsite.com/callback_link"
addrs: 2NF2baYuJAkCKo5onjUKEPdARQkZ6SYyKd5,2NAre8sX2povnjy4aeiHKeEh97Qhn97tB1f

Thanks.

**Comment by stokito** [comment]
I'l do it today and send PR

**Comment by zekylaf** [comment]
I need the same

**Comment by nbabenko** [comment]
not actual anymore, closing the issue. Please reopen anyone who still needs it
