### ISSUE TITLE
/api/tx/:tx_hash Wrong scriptSig on transaction input

### ISSUE THREAD

**Issue by foowie** [bitpay/insight-api#423]
There is something wrong with new insight-api transaction data (using bitcore-node) on transaction dd6fabd2d879be7b8394ad170ff908e9a36b5d5d0b394508df0cca36d2931589

"[Old](https://insight.bitpay.com/api/tx/dd6fabd2d879be7b8394ad170ff908e9a36b5d5d0b394508df0cca36d2931589)" insight-api returned 
```
0
3045022100beb1d83771c04faaeb40bded4f031ed0e0730aaab77cf70102ecd05734a1762002206f168fb00f3b9d7c04b8c78e1fc11e81b9caa49885a904bf22780a7e14a8373101
3045022100a319839e37828bf164ff45de34a3fe22d542ebc8297c5d87dbc56fc3068ff9d5022077081a877b6e7f104d8a2fe0985bf2eb7de2e08edbac9499fc3710a353f6546101
522103a70ae7bde64333461fb88aaafe12ad6c67ca17c8213642469ae191e0aabc7251210344a62338c8ddf138771516d38187146242db50853aa588bcb10a5e49c86421a52102b52a1aed304c4d6cedcf82911f90ca6e1ffed0a5b8f7f19c68213d6fcbde677e53ae
```
as a asm script sig on input.

"[New](http://52.18.194.185:3001/api/tx/dd6fabd2d879be7b8394ad170ff908e9a36b5d5d0b394508df0cca36d2931589)" insight-api returns
```
OP_0
3045022100beb1d83771c04faaeb40bded4f031ed0e0730aaab77cf70102ecd05734a1762002206f168fb00f3b9d7c04b8c78e1fc11e81b9caa49885a904bf22780a7e14a8373101
3045022100a319839e37828bf164ff45de34a3fe22d542ebc8297c5d87dbc56fc3068ff9d5022077081a877b6e7f104d8a2fe0985bf2eb7de2e08edbac9499fc3710a353f6546101
OP_PUSHDATA1
522103a70ae7bde64333461fb88aaafe12ad6c67ca17c8213642469ae191e0aabc7251210344a62338c8ddf138771516d38187146242db50853aa588bcb10a5e49c86421a52102b52a1aed304c4d6cedcf82911f90ca6e1ffed0a5b8f7f19c68213d6fcbde677e53ae
```
The issue is "OP_PUSHDATA1". Because of that, pycoin generates invalid transaction with different hash. Also [blockchain](https://blockchain.info/tx/dd6fabd2d879be7b8394ad170ff908e9a36b5d5d0b394508df0cca36d2931589) has no OP_PUSHDATA1 in the input script.

**Comment by braydonf** [comment]
Thanks for reporting the inconsistency. The issue may be near: https://github.com/bitpay/bitcore-lib/blob/master/lib/script/script.js#L261

**Comment by braydonf** [comment]
Added this to the test suite at: https://github.com/bitpay/bitcore-lib/pull/19 and a patch should be on it's way shortly.

**Comment by braydonf** [comment]
PR updated with a patch: https://github.com/bitpay/bitcore-lib/pull/19

**Comment by braydonf** [comment]
@foowie the scriptSig is now coming directly from bitcoind, so it shouldn't differ from those results. Also it may be a good idea to parse the hex, as this is more direct serialization format.
