### ISSUE TITLE
Verify Messages Problem

### ISSUE THREAD

**Issue by uiucgrad** [bitpay/insight-api#425]
For some messages when I try to verify I am receiving the message "Unexpected error: Invalid Argument: Error: s must be 32 bytes. Code:1"  The same information will verify in Bitcoin-qt.

For Example:
/insight-api/messages/verify?message=VerifyAddr&address=1HTe96ogbCuc1aH1k7pRpKHf6PyJwHN1j9&signature=INT80M0JrhD4e34X6DbfXu6GaIk8HGfA0Z03hUzDOc3nYIsH7jV3ATH8DxRB+f1Ol739ToL+FGy582Xd6olaNts=

**Comment by braydonf** [comment]
Base64 signature needs to be URL encoded.

**Comment by braydonf** [comment]
Perhaps this should be documented?

**Comment by uiucgrad** [comment]
Yes, now that you point it out, its obvious.  Thanks!
