### ISSUE TITLE
Return an error when querying for a mainnet address on a testnet deployment

### ISSUE THREAD

**Issue by Levino** [bitpay/insight-api#432]
Currently one only gets a reply like "not txs happend on this address". It should return something like "wrong network buddy".

If you wanna test: https://test-insight.bitpay.com/api/addr/1CK6KHY6MHgYvmRQ4PAafKYDrg1ejbH1cE

**Comment by braydonf** [comment]
Related and possible duplicate: https://github.com/bitpay/insight/issues/686

**Comment by braydonf** [comment]
This returns an error: `Invalid address. Code:-5`
