### ISSUE TITLE
block height in transaction request

### ISSUE THREAD

**Issue by hyzhak** [bitpay/insight-api#433]
Please add block height in transaction request. I need to get it in my app and to archive it I'm doing 2 http requests right now.

**Comment by wizardofozzie** [comment]
I moved onto Blockcypher's API (from blockexplorer.com) due to identical issues.

Similarly, I was making [2 http calls](https://github.com/wizardofozzie/pybitcointools/blob/289fa08aa9e31b25126a96cb1225ff1d2e808d9e/bitcoin/bci.py#L354-L360)
