### ISSUE TITLE
Warning: This version is obsolete; upgrade required!

### ISSUE THREAD

**Issue by zekylaf** [bitpay/insight-api#436]
Hi, I am getting this message "Warning: This version is obsolete; upgrade required!" in http://<insight-server>:3001/insight-api/status

but I don`t know what does it means. What I have to to? 

Thanks

**Comment by braydonf** [comment]
What version are you running?

**Comment by zekylaf** [comment]
Latest version. In info it says:

{"info":{"version":110100,"protocolversion":70002,"blocks":386424,"timeoffset":-2,"connections":19,"difficulty":72722780642.54718,"testnet":false,"relayfee":5000,"errors":"Warning: This version is obsolete; upgrade required!"}}

**Comment by braydonf** [comment]
test-insight.bitpay.com is currently showing:
```

**Comment by braydonf** [comment]
We have a version with bitcoind 0.11.2 that hasn't been released yet, but is on master, however I doubt that is an issue. However it would be good to release that anyways.

**Comment by zekylaf** [comment]
Ok, thanks you!

**Comment by braydonf** [comment]
Upgraded to 0.12.0 of bitcoin.

**Comment by periodic1236** [comment]
@braydonf The message still appears since Bitcoin Core version 0.12.1 has been out for a while and it includes a softfork (BIP9, BIP68, BIP112).
