### ISSUE TITLE
Cannot get /

### ISSUE THREAD

**Issue by EBTCoin** [bitpay/insight-api#440]
Hello,

I recently installed Bitcore and Insight API on an Ubuntu 14.04 LTS VM and when I go to http://localhost:3001/ I get "Cannot get /".

I am using Node v4.2.2.

Any help would be greatly appreciated!

Thank you.

**Comment by braydonf** [comment]
The path for the service is located at `/insight-api/`, as mentioned on the README. There is an open issue to add something to the base route: https://github.com/bitpay/bitcore-node/issues/272

**Comment by roddyofchina** [comment]
I am also experiencing this problem ，Node v4.1.2
