### ISSUE TITLE
tx/send error - "503 Service Unavailable"

### ISSUE THREAD

**Issue by hideoussquid** [bitpay/insight-api#441]
I have a bitcore-node server set up and running, it's performing well when it comes to getting address data from the api. The one thing it will NOT do is send transactions. Whenever I try to send a transaction via the api (POST data), it comes back with "503 Service Unavailable".
Exact error received:
````
{"readyState":4,"responseText":"TX decode failed","status":503,"statusText":"Service Unavailable"}
````
I took the raw signed hex from this transaction and submitted it via the "broadcast transaction" pane of the same server's insight-ui - and it sends instantly.

I tried another transaction that fails via my api (same fees, same inputs/outputs) and submit it via https://insight.bitpay.com/api - the transaction works flawlessly. Fees are more than enough (checked against the internal fee calculator) and all inputs are confirmed.

Services running on the active instance:
````
 "services": [
    "address",
    "bitcoind",
    "db",
    "insight-api",
    "insight-ui",
    "web"
  ],
````
Is there some other way to activate the tx/send feature?

Status report for my server:
````
{"info":
    {
    "version":110200,
    "protocolversion":70002,
    "blocks":388578,
    "timeoffset":0,
    "connections":33,
    "difficulty":79102380900.22598,
    "testnet":false,
    "relayfee":5000,
    "errors":""
    }
}
````

**Comment by dabura667** [comment]
I had the same problem. Am running the same version as OP, but without insight-ui.

**Comment by Derrick-** [comment]
I had the same problem and it was caused by lack of headers on the request.
Ensure that your Content-Length is set, and Content-Type is "application/x-www-form-urlencoded"

**Comment by braydonf** [comment]
Also application/json encoding should work:
`curl -H "Content-Type: application/json" -X POST -d '{"rawtx": "[hexstring]"}' https://test-insight.bitpay.com/api/tx/send`
