### ISSUE TITLE
Seems as though there's a problem querying transactions for a block

### ISSUE THREAD

**Issue by ScroogeMcDuckButWithBitcoin** [bitpay/insight-api#443]
Any queries of the form: https://insight.bitpay.com/api/txs/?block=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f

Cause a cloudfire 504/timeout.

**Comment by hideoussquid** [comment]
Must be their site configuration, as I'm running an instance and it returns just fine:
http://bitlox.io/api/txs/?block=000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f

**Comment by dabura667** [comment]
My private instance is also fine...

must be a cloudfire issue?

**Comment by hideoussquid** [comment]
Appears so. Since you are running a private instance, may I ask if you are having an issue sending raw transactions via tx/send as I am in this open issue? https://github.com/bitpay/insight-api/issues/441

**Comment by dabura667** [comment]
I had the same problem just now.

**Comment by ScroogeMcDuckButWithBitcoin** [comment]
Seems like bitpay started working again - @hideoussquid , I think the reason you were working and they were not is because they're returning the entire block, whereas you were returning smaller pages. (And the execution time to return the whole page exceeded the cloudfire timeout threshold.

Here's my code/project, for the curious: https://github.com/ScroogeMcDuckButWithBitcoin/node-dropzone/blob/master/lib/drivers/insight.js

Also, @hideoussquid - is there any chance you'd be adding ssl support at some point?
