### ISSUE TITLE
Can't send tx with your api

### ISSUE THREAD

**Issue by unlimitedunlimited** [bitpay/insight-api#446]
Can't send tx with your api. I tried using both curl and postman but I get an error.
For example the following 'curl -d {"rawtx":"mytx"} https://insight.bitpay.com/api/tx/send', gives me the error 'parameter must be hexadecimal string (not '') (code -8)'

**Comment by braydonf** [comment]
This curl command should work:
`curl -H "Content-Type: application/json" -X POST -d '{"rawtx": "[hexstring]"}' http://test-insight.bitpay.com/api/tx/send`
