### ISSUE TITLE
Error handling/Validation problem in /addrs/utxo

### ISSUE THREAD

**Issue by matiu** [bitpay/insight-api#448]
curl -H "Content-Type: application/json" -X POST -d '{"xxx"}'  http://URL/api/addrs/utxo

SyntaxError: Unexpected token }<br> &nbsp; &nbsp;at Object.parse (native)<br> &nbsp; &nbsp;at parse (/home/insight/insight/node_modules/bitcore-node/node_modules/body-parser/lib/types/json.js:88:17)<br> &nbsp; &nbsp;at /home/insight/insight/node_modules/bitcore-node/node_modules/body-parser/lib/read.js:116:18<br> &nbsp; &nbsp;at invokeCallback (/home/insight/insight/node_modules/bitcore-node/node_modules/body-parser/node_modules/raw-body/index.js:262:16)<br> &nbsp; &nbsp;at done (/home/insight/insight/node_modules/bitcore-node/node_modules/body-parser/node_modules/raw-body/index.js:251:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/home/insight/insight/node_modules/bitcore-node/node_modules/body-parser/node_modules/raw-body/index.js:308:7)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:104:17)<br> &nbsp; &nbsp;at _stream_readable.js:908:16<br> &nbsp; &nbsp;at process._tickCallback (node.js:355:11)

**Comment by braydonf** [comment]
Looks like a JSON parsing error, and are responding with "HTTP/1.1 400 Bad Request" error. With NODE_ENV=production this should be visible as only "Bad Request".
