### ISSUE TITLE
Public Insight is not working?

### ISSUE THREAD

**Issue by troggy** [bitpay/insight-api#450]
It reports
````
Can't connect to bitcoind to get live updates from the p2p network. (Tried connecting to bitcoind at localhost:8333 and failed.)
````
on https://insight.bitpay.com/status

**Comment by matiu** [comment]
it should be ok now, thanks for the report.

On Wed, Feb 3, 2016 at 11:59 AM, Kosta Korenkov <notifications@github.com>
wrote:

> It reports
>
> Can't connect to bitcoind to get live updates from the p2p network (Tried connecting to bitcoind at localhost:8333 and failed)
>
> on https://insightbitpaycom/status
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/insight-api/issues/450>.
>



-- 
BitPay.com
