### ISSUE TITLE
Performance problems during transactions processing

### ISSUE THREAD

**Issue by vdidonato** [bitpay/insight-api#452]
Good morning everyone, 
I noticed that while my bitcore-node is processing transactions, insight-api stops answering to queries. The requests sometimes pend for up to 3-4 minutes. 

So, my question is: is there a way to pause the sync process so to have insight-api up&running at full speed? I'm thinking something like: sync in the night and pause in the day. 

I am not sure if this is a question for bitcore-node developers or insight-api. 
Thanks

**Comment by braydonf** [comment]
Is this during the initial sync process?

**Comment by vdidonato** [comment]
No, while it is up & running.

**Comment by braydonf** [comment]
The sync only runs once every ten minutes on average, and should take less than a second. Are there any other expensive queries being run?

**Comment by vdidonato** [comment]
Really? I don't know what is happening then. That particular machine has only bitcore-node running and its process takes 100% of the cpu for 3-4 minutes at regular intervals. If you say that it should only take a second...there must be something wrong with my configuration or something...

**Comment by braydonf** [comment]
Did it take longer than 24 to 48 hours for the initial sync?

**Comment by vdidonato** [comment]
no, I did it about two months ago, but if I remember correctly it took less than 48 hours. Maybe I could download the latest version and try with a fresh start...

**Comment by braydonf** [comment]
There is also work-in-progress to improve performance at (using bitcoind to build indexes):
- https://github.com/bitpay/bitcoin/pull/6 
- https://github.com/bitpay/bitcore-node/pull/422
- https://github.com/bitpay/insight-api/pull/467

**Comment by braydonf** [comment]
If you can reproduce the issue, it would be worth digging in to see what the CPU is doing. Have you attached `node-inspector` to take a look?

**Comment by braydonf** [comment]
Indexes are built in bitcoind now, please let us know if you still have any issues.
