### ISSUE TITLE
Possible error in confirmations / orphaned

### ISSUE THREAD

**Issue by matiu** [bitpay/insight-api#458]
https://test-insight.bitpay.com/block/000000003441587ce84ccbfb71582e30c5f6123bbf43438af685a60c926f4633

the block is marked as orphaned, but the TX has many confirmation. Clicking the tx, shows:

Included in Block	
000000003441587ce84ccbfb71582e30c5f6123bbf43438af685a60c926f4633

which is the orphaned block.

Other BE also show the block as orphan:
https://www.blocktrail.com/tBTC/block/000000003441587ce84ccbfb71582e30c5f6123bbf43438af685a60c926f4633

**Comment by braydonf** [comment]
Relevant code: https://github.com/bitpay/bitcore-node/blob/master/src/libbitcoind.cc#L1229
