### ISSUE TITLE
Maximum number of inputs (50000) per query reached

### ISSUE THREAD

**Issue by vivek0** [bitpay/insight-api#459]
This shows now wasn't showing a few mins ago on Bitpay website as well. 

https://insight.bitpay.com/address/1MEe2mebed8wopvy8xyjjHcEQHUPVJn2UC

Localhost query still gives 

> Backend Error. Maximum number of inputs (50000) per query reached

**Comment by braydonf** [comment]
The maximum can be increased locally by passing an option into the bitcore-node.json config for the address module:
```
servicesConfig: {
  address: {
    maxInputsQueryLength: <max>,
    maxOutputsQueryLength: <max>
  }
}
```

**Note:** We're currently working on optimizing indexes so that the number of outputs/inputs won't affect the performance of queries.

**Comment by vivek0** [comment]
Thanks for that Bradon, Any optimal number you could suggest for fellow users out here?

I'm doubling it for now.

**Comment by ByronAP** [comment]
paging doesn't work on /addr/1dice97ECuByXAvqXpaYzSaQuPVvrtmz6
