### ISSUE TITLE
Transaction: Received time = Mined time. Bug?

### ISSUE THREAD

**Issue by zekylaf** [bitpay/insight-api#465]
Hi, I need to know if it is a bug.

If you check the details of a transaction, you will find that the received time and mined time are the same.

For example:

https://insight.bitpay.com/tx/b63450f565d1db94f23b5fde62c43add5cb16ba6e19263786483dd0d00b57efc

Thanks

**Comment by zekylaf** [comment]
@braydonf can you confirm if it is a bug?

**Comment by braydonf** [comment]
Received time I believe may only apply for unconfirmed transactions that do not have a mined time.

**Comment by newbyprogrammer** [comment]
Hi, thanks for answer.

Do you know if there is anyway to know the 'received time' after the tx is mined?

**Comment by zekylaf** [comment]
Hi, thanks for answer

Do you know if there is anyway to know the 'received time' after the tx is mined?

**Comment by braydonf** [comment]
I don't, all information comes from the blockchain, and the transaction time is really the block timestamp.

**Comment by zekylaf** [comment]
Ok, thanks for answer
