### ISSUE TITLE
Add raw block endpoint

### ISSUE THREAD

**Issue by gabegattis** [bitpay/insight-api#474]
Currently, there is no way to get an actual block from the insight api. The api/block/[:hash] endpoint does not return a proper block. It just includes header, metadata, and an array of txids. We should add a new endpoint for fetching the raw block hex. The results can be parsed by bitcore on the client side.

**Comment by braydonf** [comment]
These two endpoints could work well as similar to `/rawtx/<hash>`:
```
/rawblock/<height>
/rawblock/<hash>
```

**Comment by braydonf** [comment]
Added in: https://github.com/bitpay/insight-api/issues/474
