### ISSUE TITLE
Bug: Genesis block shows -1 as previous block

### ISSUE THREAD

**Issue by gabegattis** [bitpay/insight-api#476]
https://test-insight.bitpay.com/block/000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943 is the genesis block for testnet. It shows block # -1 as the previous block.
![testgenesis](https://cloud.githubusercontent.com/assets/4419243/14509555/de8901a4-019a-11e6-871e-08e44b23f137.png)

**Comment by braydonf** [comment]
This is showing up because the prevHash is `0000000000000000000000000000000000000000000000000000000000000000` from bitcore-lib `BlockHeader.prototype.toObject()` method, which is truthy.

**Comment by gabegattis** [comment]
sigh
![file_truthiness](https://cloud.githubusercontent.com/assets/4419243/14573219/a810c732-0321-11e6-88c1-37076b8ea78a.png)

**Comment by gabegattis** [comment]
sigh
![truthiness](https://cloud.githubusercontent.com/assets/4419243/14573238/c6dd2dc2-0321-11e6-8775-09bd87414636.png)

**Comment by braydonf** [comment]
Fixed in https://github.com/bitpay/insight-api/pull/467
