### ISSUE TITLE
Add Rate Limiter Options

### ISSUE THREAD

**Issue by kabutosamourai** [bitpay/insight-api#482]
The rate limiter is [created](https://github.com/bitpay/insight-api/blob/master/lib/index.js#L124) by passing a single option:

`var limiter = new RateLimiter({node: this.node});`

Even though the limiter supports more options such as IP white listing.

Please enable options configuration for the rate limiter, or the ability to disable it.

**Comment by braydonf** [comment]
Good catch, we should be able to pass in options.

**Comment by braydonf** [comment]
Added in https://github.com/bitpay/insight-api/pull/484/files

**Comment by braydonf** [comment]
Landed in 0.4.2

**Comment by kabutosamourai** [comment]
Well done. Works perfectly!

**Comment by usab** [comment]
I think the rate limiter does not work correctly.

I added

```
  "servicesConfig": {
    "web": {
      "jsonRequestLimit": "200kb"
    }
  }
```
to my bitcore-node.json and restartet the service. I still get this message after a while:

> failed to open stream: HTTP request failed! HTTP/1.1 429 Too Many Requests

**Comment by usab** [comment]
Got it:

in ratelimitier.js is a hard coded litmit:
change
`totalRequests: options.limit || 3 * 60 * 60 * 10`
to
`totalRequests: options.limit || 3 * 60 * 60 * 10 * [big number]`
