### ISSUE TITLE
UTXO Confirmations is Negative

### ISSUE THREAD

**Issue by kabutosamourai** [bitpay/insight-api#483]
It seems that `this.node.services.bitcoind.height` is not updating properly, resulting in negative values for the number of confirmations for UTXOs. Perhaps it retains the value at startup (matching the result from the obsolete `/sync` API endpoint)?

https://github.com/bitpay/insight-api/blob/master/lib/addresses.js#L162

**Comment by braydonf** [comment]
It should stay updated when there is a new block (see https://github.com/bitpay/bitcore-node/blob/master/lib/services/bitcoind.js#L522-556), were there any other errors before hand?

**Comment by kabutosamourai** [comment]
Bitcoind's `debug.log` contains multiple lines of `ERROR: unable to get spent info`
`, though it continued to produce `UpdateTip` messages. Bitcore's output of the latest blocks stopped updating however. But much of the screen output changed after the bump to 4.0.

Insight API working properly otherwise. Where else are errors found?

**Comment by braydonf** [comment]
`ERROR: unable to get spent info` Is actually okay, since some outputs/inputs will not have spent info.

You're connect via ZMQ to bitcoind?, you should see a log message such as:
`[2016-06-01T16:15:51.539Z] info: ZMQ connected to: tcp://127.0.0.1:28332`

**Comment by kabutosamourai** [comment]
Yes, ZMQ is connected properly.

**Comment by kabutosamourai** [comment]
Not on this install of Bitcore (4.0). Those messages were on the previous version.

**Comment by braydonf** [comment]
What does `/insight-api/sync` return?

**Comment by kabutosamourai** [comment]
```json
{
  "status":"finished",
  "blockChainHeight":414349,
  "syncPercentage":100,
  "height":414349,
  "error":null,
  "type":"bitcore node"
}
```
The two height measures reflect the height at startup and never seem to change. Calls to `/status` produce updating numbers as new blocks come in.

**Comment by braydonf** [comment]
It sounds like the zmq event for hashblock isn't working. Your `bitcoin.conf` has both `zmqpubrawtx` and `zmqpubhashblock`?:
```
zmqpubrawtx=tcp://127.0.0.1:28332
zmqpubhashblock=tcp://127.0.0.1:28332
```
Can you confirm that you're getting zmq "hashblock" events, and that the `_zmqBlockHandler` is being called when there is a new block at https://github.com/bitpay/bitcore-node/blob/master/lib/services/bitcoind.js#L488-505 ? You may need to add additional log message.

**Comment by kabutosamourai** [comment]
Both of those configuration options were set, but the **ports were different**. Changing both options to the same port seems to have fixed the problem.

Perhaps a note in the [upgrade docs](https://github.com/bitpay/bitcore-node/blob/master/docs/upgrade.md) would help? Seems easier than changing to code to accommodate two different ports for those ZMQ endpoints.

**Comment by braydonf** [comment]
We can also put a precondition to specify that the ports are the same, and monitoring that the event is subscribed.
