### ISSUE TITLE
How to decode serialized blocks?

### ISSUE THREAD

**Issue by vdidonato** [bitpay/insight-api#486]
As documented in the front page there is a new GET endpoint to get the raw blocks. 
Now, how do I decode the serialized block? Do you have any experiences? Thanks

**Comment by braydonf** [comment]
That depends on the library you're using. If you're using [bitcore-lib](https://github.com/bitpay/bitcore-lib), see: https://github.com/bitpay/bitcore-lib/blob/master/docs/block.md

**Comment by vdidonato** [comment]
I see. I'm actually new to bitcore-node and insight-api. 
I was trying to understand how this works but I'm having a hard time. 
I tried to save a block hash in block.json and I was expecting this example to work:

```
var bitcore = require("bitcore-lib");
var block_data = require("./block.json");
var Block = bitcore.Block
var bl = Block(block_data["rawblock"]);
console.log(bl)
```

but I'm getting "TypeError: Unrecognized argument for Block" and I don't understand why...given that your link says:

```
// instantiate a new block instance
var block = new Block(hexaEncodedBlock);
```

**Comment by dabura667** [comment]
You can't just pass the block hash, you must pass the entire block encoded in hex.

**Comment by vdidonato** [comment]
That's what I did (my block.json is the output of the new GET endpoint).
I think the documentation of bitcore-lib is just wrong and you can't actually pass in the entire block encoded in hex. 

If you look at the code in bitcore-lib/lib/block/block.js, it looks like the input must be either a Buffer, or a javscript Object that contains all the data explicitly.

The relevant parts:

```
/**
 * @param {*} - A Buffer, JSON string or Object
 * @returns {Object} - An object representing block data
 * @throws {TypeError} - If the argument was not recognized
 * @private
 */
Block._from = function _from(arg) {
  var info = {};
  if (BufferUtil.isBuffer(arg)) {
    info = Block._fromBufferReader(BufferReader(arg));
  } else if (_.isObject(arg)) {
    info = Block._fromObject(arg);
  } else {
    throw new TypeError('Unrecognized argument for Block');
  }
  return info;
};
```

and 

```
/**
 * @param {Object} - A plain JavaScript object
 * @returns {Object} - An object representing block data
 * @private
 */
Block._fromObject = function _fromObject(data) {
  var transactions = [];
  data.transactions.forEach(function(tx) {
    if (tx instanceof Transaction) {
      transactions.push(tx);
    } else {
      transactions.push(Transaction().fromObject(tx));
    }
  });
```

**Comment by braydonf** [comment]
You may need to use:
```js
var block = Block.fromString()
```
The documentation for blocks could be expanded and improved, and the API of block improved. Spawned an issue for that: https://github.com/bitpay/bitcore-lib/issues/81
