### ISSUE TITLE
Error 413

### ISSUE THREAD

**Issue by got3nks** [bitpay/insight-api#489]
After generating a lot of addresses, I can no longer check balance.

```
WARN Insight http://46.28.204.68:3001/insight-api/addrs/utxo Returned Status: 413
ERR! /v1/balance/?r=19217 :500:Error querying the blockchain
 127.0.0.1 2016-07-20T09:03:48.484Z "GET /bws/api/v1/balance/?r=19217" 500 41 88.659 "-" 9c72a87d-7071-444a-a32c-debc26ee0628 ab20ba53eabd4434d5d4710cafcd8778c9a175e4ce7978c75a15fb33ace4e867
```

I'm running my own Bitcore + Insight API, how do I lift this limit? I need to generate unlimited deposit addresses for our web application. We can't limit the amount of addresses and we need to be able to check all generated addresses, as they are being used as deposit addresses.

**Comment by matiu** [comment]
See https://github.com/bitpay/insight-api/pull/484

**Comment by matiu** [comment]
Added to Readme at https://github.com/bitpay/insight-api/blob/master/README.md#query-rate-limit

thanks!

**Comment by got3nks** [comment]
This is not the same issue. My Bitcore node configuration file already looks like this:

```
  "servicesConfig": {
    "bitcoind": {
      "spawn": {
        "datadir": "/home/cryptos/.bitcore/data",
        "exec": "/usr/local/lib/node_modules/bitcore/node_modules/bitcore-node/bin/bitcoind"
      }
    }, "insight-api": {
      "disableRateLimiter": true
    }
  }
```

The problem to me looks like related to Express. I tried to edit the file **/usr/lib/node_modules/bitcore/node_modules/insight-api/lib/index.js** adding these lines:

```
  var jsonParser       = bodyParser.json({limit:1024*1024*50, type:'application/json'});
  var urlencodedParser = bodyParser.urlencoded({ extended:true,limit:1024*1024*50,type:'application/x-www-form-urlencoding' })
  app.use(jsonParser);
  app.use(urlencodedParser);
```

But it's not working yet. Any idea?

**Comment by braydonf** [comment]
This may be for the size of the request payload "413 Payload Too Large", instead of "429 Too Many Requests", and this option applies: https://github.com/bitpay/bitcore-node/pull/458

**Comment by got3nks** [comment]
Thank you braydonf, this worked.

I have another issue now though:
```
[error] Error: Error querying the blockchain
error: Error while opening wallet:  Error: Error querying the blockchain
    at Function.API._parseError (/home/bitcore/node_modules/bitcore-wallet-client/lib/api.js:263:11)
    at Request._callback (/home/bitcore/node_modules/bitcore-wallet-client/lib/api.js:792:21)
    at Request.self.callback (/home/bitcore/node_modules/bitcore-wallet-client/node_modules/request/request.js:187:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/home/bitcore/node_modules/bitcore-wallet-client/node_modules/request/request.js:1044:10)
    at Request.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (/home/bitcore/node_modules/bitcore-wallet-client/node_modules/request/request.js:965:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
sh-4.1$ node bitcoin_wallet.js
error: Error while opening wallet:  connection error
Error
    at Error.NodeError (/home/bitcore/node_modules/bitcore-wallet-client/lib/errors/index.js:20:41)
    at Request._callback (/home/bitcore/node_modules/bitcore-wallet-client/lib/api.js:782:17)
    at self.callback (/home/bitcore/node_modules/bitcore-wallet-client/node_modules/request/request.js:187:22)
    at Request.emit (events.js:95:17)
    at null._onTimeout (/home/bitcore/node_modules/bitcore-wallet-client/node_modules/request/request.js:762:12)
    at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
```

How can I increase the timeout time?

I'm wondering if keep using BWS as our wallet is either a good idea or not. Our web service is generating an average of over 100 deposit addresses daily. How do I make sure it won't get too huge to be handled?

**Comment by braydonf** [comment]
FYI, this a use-case we're looking at improving. 

As for timeouts *(not sure on the setting there)*, but here are some addition log locations to monitor for activity:
- /path/to/bitcoin/datadir/blocks/index/LOG
- /path/to/bitcoin/datadir/debug.log (with debug=1 in bitcoin.conf)

**Comment by usab** [comment]
Getting this error: 429 Too Many Requests
How can I change my config to allow more requests? I am running my own insight server and I would like to increase the limit for the number of requests.

**Comment by usab** [comment]
Got it!

Just add this in bitcore-node.json:

  "servicesConfig": {
    "insight-api": {
      "disableRateLimiter": true
    }
  }

**Comment by usab** [comment]
I disabled the rate limiter but still get the following error after a while:

> failed to open stream: HTTP request failed! HTTP/1.1 429 Too Many Requests

bitcore-node.json:
```
...
  "servicesConfig": {
    "web": {
      "jsonRequestLimit": "200kb"
    }
  },
...
```

**Comment by Nuc7ear** [comment]
I do it and find same error on web for help. and i see your massege. Goddness i lost over 4 hours for it. If i look this link first i do it so fast. But i do it same xD

**Comment by Smurfy303** [comment]
Hi @got3nks , How you connect Bitcore + Insight API ?? Please help me to sort this, you can answer me on question ->  https://github.com/bitpay/insight-api/issues/577
