### ISSUE TITLE
No history for 14sKjXZTLqcW2KQTDGkJnZWk4TtcNqLMJm

### ISSUE THREAD

**Issue by bitcoinsSG** [bitpay/insight-api#497]
Found a weird error, might be a tip of a larger iceberg. However, there seems to be no history for address 14sKjXZTLqcW2KQTDGkJnZWk4TtcNqLMJm, it should have a coinbase transaction in block 28975 and several others afterwards

try:
https://insight.bitpay.com/address/14npkL1YMYjeMaPPGY5ZMN8VozJpTgG2Dg
vs.
https://blockchain.info/address/14sKjXZTLqcW2KQTDGkJnZWk4TtcNqLMJm

**Comment by braydonf** [comment]
It's likely because pay-to-publickey is not indexed, since there isn't an address, and it's paying directly to the public key and not the hash.

**Comment by bitcoinsSG** [comment]
makes sense
