### ISSUE TITLE
Insight API also accessible as REST API?

### ISSUE THREAD

**Issue by SuperHenkie** [bitpay/insight-api#498]
As a human user, I can visit https://insight.bitpay.com/ and the block explorer interface. For example, I can look up the details on an address [like this](https://insight.bitpay.com/address/12c6DSiU4Rq3P4ZxziKxzrL5LmMBrzjrJX). Works great.

Does it also provide REST API access, e.g. can I call the API endpoints from a remote location?

For example, from my own webserver can I retrieve something like `https://insight.bitpay.com/api/address/12c6DSiU4Rq3P4ZxziKxzrL5LmMBrzjrJX` to get that particular address' details in json format?

**Comment by matiu** [comment]
yes. see https://github.com/bitpay/insight-api for the endpoints.

**Comment by SuperHenkie** [comment]
Thanks, but what would be the actual, full URL for such an API call? 

I tried these:
`http://insight.bitpay.com/insight-api/address/12c6DSiU4Rq3P4ZxziKxzrL5LmMBrzjrJX`
`http://insight.bitpay.com:3000/insight-api/address/12c6DSiU4Rq3P4ZxziKxzrL5LmMBrzjrJX`
`https://insight.bitpay.com/insight-api/address/12c6DSiU4Rq3P4ZxziKxzrL5LmMBrzjrJX`
`https://insight.bitpay.com:3000/insight-api/address/12c6DSiU4Rq3P4ZxziKxzrL5LmMBrzjrJX`

And similar attempts for other endpoints (e.g. `/block-index/123456` etc) but same results: web interface works fine, but can't find the corresponding API (REST) URL.

**Comment by RobertBaron** [comment]
Hi Super,

So for that you  can find the calls in the Network tab of your dev tools.
Here a sample:

https://insight.bitpay.com/api/txs?block=000000000000000001789e91cd8bb45c297c350f051fedde3358d4ec770ae83e&pageNum=0

So the root of the endpoint for that domain is: https://insight.bitpay.com/api/

*Sorry for my bad english, not a native speaker

**Comment by SuperHenkie** [comment]
Thanks, I think I got it!

**Comment by blockchainguyy** [comment]
@RobertBaron @SuperHenkie @matiu The above-mentioned URL does not work now, can you help me with the new URL exposed for insight APIs?
