### ISSUE TITLE
How to run insight-api in testnet?

### ISSUE THREAD

**Issue by thosuperman** [bitpay/insight-api#503]
Hi all, I'm sorry if this question make trouble for you.

Would you please guide me how to run insight-api in testnet? I've tried installing by command:

`npm install bitcore`

and run by:

`pm2 start node_modules/bitcore/bin/bitcored`

But it's livenet.

Thanks so much.

**Comment by dabura667** [comment]
--testnet

**Comment by thosuperman** [comment]
@dabura667: Thank you so much.

**Comment by thosuperman** [comment]
I got the error 

> unknown option --testnet

with command

`pm2 start node_modules/bitcore/bin/bitcored --testnet`

**Comment by thosuperman** [comment]
We need to modify bitcore-node.json inside /home/your_user_name/.bitcore/ to change it to testnet
