### ISSUE TITLE
Cannot GET 

### ISSUE THREAD

**Issue by roddyofchina** [bitpay/insight-api#509]
I encountered a problem after starting 。
Cannot GET /insight-api/

node 

[root@localhost mynode]# cat package.json 
{
  "description": "A full Bitcoin node build with Bitcore",
  "repository": "https://github.com/user/project",
  "license": "MIT",
  "readme": "README.md",
  "dependencies": {
    "bitcore-lib": "^v0.13.19",
    "bitcore-node": "^3.1.3",
    "insight-api": "^0.4.3",
    "insight-ui": "^0.4.0"
  }
  "insightConfig": {
    "apiPrefix": "insight-api",
    "routePrefix": "insight"
  }
}

[root@localhost mynode]# cat bitcore-node.json 
{
  "network": "livenet",
  "port": 3001,
  "services": [
    "bitcoind",
    "insight-api",
    "insight-ui",
    "web"
  ],
  "servicesConfig": {
    "bitcoind": {
      "spawn": {
        "datadir": "./data",
        "exec": "/tmp/bitcore-node/bin/bitcoind"
      }
    }
  }
}[root@localhost mynode]#

**Comment by roddyofchina** [comment]
it's ok

**Comment by l0rb** [comment]
And how did you fix this?

**Comment by xelawafs** [comment]
Worked for me when I restarted bitcired. I'd actually advice to restart the server just to be sure and watch out for this on the logs
<img width="252" alt="screen shot 2018-01-18 at 02 53 40" src="https://user-images.githubusercontent.com/35254822/35075299-ff28b2fe-fbfa-11e7-82bb-3ea924cb38f1.png">
