### ISSUE TITLE
Can not get the input address and value when running the bcc node

### ISSUE THREAD

**Issue by siuu** [bitpay/insight-api#515]
I can not get the input address, value, confirmations when running the bitcoinabc-0.14.6
![image](https://user-images.githubusercontent.com/17903971/29154924-cdbc58d2-7dca-11e7-9e63-e718654d4319.png)

![image](https://user-images.githubusercontent.com/17903971/29154931-d9f69d06-7dca-11e7-9488-8a8e51adb8fd.png)

![image](https://user-images.githubusercontent.com/17903971/29154955-06087220-7dcb-11e7-9185-a9dc56e8f78a.png)

**Comment by dabura667** [comment]
You need to change the signature matching to account for the new sighash.

**Comment by siuu** [comment]
@dabura667 I'm sorry, I don‘t know how to do that.Can u tell me in detail?
