### ISSUE TITLE
No initial accounts/transactions information

### ISSUE THREAD

**Issue by bearxu83** [bitpay/insight-api#520]
For example, account: Xo9UzA2B7yyEhsrQZyFPGCTuFbNGKgHkPU
tx: e0028eb9648db56b1ac77cf090b99048a8007e2bb64b68f092c03c7f56a662c7

Dash-insight showed no historical records about it. 
But if use Dash block explorer, we can search it.

**Comment by marint94** [comment]
@bearxu83 how did you fix it?

**Comment by nmarley** [comment]
@marint94 This information is for the Dash blockchain/Insight software, and was incorrectly posted here. The issue was re-opened at https://github.com/dashpay/bitcore-node-dash/issues/18.
