### ISSUE TITLE
Incorrect balance with insight-api 

### ISSUE THREAD

**Issue by makabress** [bitpay/insight-api#521]
Hi
Im was using the old insight with ubuntu 14 until i got problem wth Ubuntu. So i decided to go with bitcore-node and insight-api. After reindexing and sync i noticed that the balance and tx of address are incorrect. I thow it's an error in my system but by verifing in insight.bitpay the problem is the same , for exemple this address:
https://insight.bitpay.com/address/1BW18n7MfpU35q4MTBSk8pse3XzQF8XvzT
Final Balance
0.00000002 BTC

And here the same address:

https://blockchain.info/fr/address/1BW18n7MfpU35q4MTBSk8pse3XzQF8XvzT

Final balance is : 50,00000002
And the transaction are not the same

So i want to return to old version and i don't remember the version that work with old insight.

Bitcoin 0.9.x??
Nodejs ???
Bower??

Can any one help me pls 
Thank you

**Comment by kleetus** [comment]
I would use what's in npm...this is the old version of insight:

npm install -g bitcore

or 

npm install -g insight-api 

(for insight-api)

**Comment by makabress** [comment]
any way the ballance in the old adresses are not correct , any solution for this ?

**Comment by marint94** [comment]
same problem @kleetus balances in old adresses are not correct

**Comment by dabura667** [comment]
I see the problem.

The problem is that Blockchain.info and most other block explorers classify P2PK and P2PKH as being the same address... when in actuality P2PK can not be sent to an address, since the address obfuscated the pubkey so a P2PK is impossible.

**Comment by marint94** [comment]
@dabura667 so you're saying (as example) the 50 BTC in an old satoshi address  can't be moved?

**Comment by dabura667** [comment]
@marint94 no, I am just saying that blockchain.info's definition of which locking scripts constitute an address differs from insight.

I personally think insight's interpretation is more correct... however, the same private key is used, so blockchain.info's interpretation is not incorrect.

It's a matter of preference.
