### ISSUE TITLE
How to run insight-api with Bitcoin cash?

### ISSUE THREAD

**Issue by NeoKings** [bitpay/insight-api#555]
I have already a Bitcoin-abc node full sync running. How to install insight-api on this node?

**Comment by NeoKings** [comment]
Done. soon I will post a link to tutorial here.

**Comment by marriva** [comment]
I was here

**Comment by wlwr** [comment]
@NeoKings I have the same problem. How do you do that.

**Comment by marriva** [comment]
I’ve fucked my brain trying do this and got no result. Help please

**Comment by ymatagne** [comment]
Hi @NeoKings, how you resolved the problem ?

**Comment by phewitt** [comment]
This would also help me!

**Comment by CerratoA** [comment]
@NeoKings Hi Neo, is there a tutorial for this?
