### ISSUE TITLE
Value error on nonstandard PK spends

### ISSUE THREAD

**Issue by periodic1236** [bitpay/insight-api#56]
When a transaction spends from a nonstandard scriptPubKey, insight is unable to parse the value of the previous output and displays "value error" instead, treating the input as unconfirmed.

Example:
http://live.insight.is/tx/09f691b2263260e71f363d1db51ff3100d285956a40cc0e4f8c8c2c4a80559b1

**Comment by braydonf** [comment]
Related: https://github.com/bitpay/bitcoin/issues/17
