### ISSUE TITLE
Blocks and Txs both published to inv

### ISSUE THREAD

**Issue by cpacia** [bitpay/insight-api#571]
I'm currently building a wallet on top of this API and I'm struggling a bit to understand some of the API design choices. 

In order to have the UI update the number of confirmations in the transaction list in real time I need to know when a new block comes in so I can push a notification with the new height to my UI. 

It would seem like the `block` socket API would work for this, but... it requires you subscribe to the `inv` room which also receives all txs for the entire network. Basically making the wallet use full node level of bandwidth. 

The only other option seems to be to repeatedly poll the `blocks` API (or transactions, etc) but that seems like a really ugly solution. 

Is there a reason why blocks have to be published to the same room as txs? Is there another way to get real time updates of the chain height that I'm missing?

Thanks

**Comment by matiu** [comment]
Hi Chris. There is a 'blocks' room. Probably it lacks documentation. Im not
at the computer now, will check later

**Comment by cpacia** [comment]
That would be excellent thanks

**Comment by matiu** [comment]
Hey, I was mistaken, it is actually only one room :/

You can check the code used by our wallet service at:
https://github.com/bitpay/bitcore-wallet-service/blob/master/lib/blockchainmonitor.js#L95

Adding a new room should be simple if you need that and want to submit a PR, I will be happy to review it and merge it.

**Comment by cpacia** [comment]
Actually I found one :p 

`bitcoind/hashblock` works for block notifications
