### ISSUE TITLE
Cannot broadcast transaction with huge amounts of inputs

### ISSUE THREAD

**Issue by SoYouDie** [bitpay/insight-api#593]
I have generated litecoin signed transaction which consist of 6 inputs. But i cant broadcast it via insight-api. The strange is the i can do it via other API like blockcypher or blockchain.info. Here is signed transaction: ```010000000622fb0c775df0608c551d5f63ba182861d0a2143798463e14a2a7042058b20693000000006a4730440220025850f5a44ca6637a602c0d15a745935bb07b9278abdc9baab9c18b05cf17120220625e0ef32e5d623643ada3b3d535e240f8cd85f2ce34930376f595218cfdf5610121034e2ec662bbc43c046c3fc4bcb80a6c522715343a1728c126469710c377b7026bffffffffead239d40350d7cb280877f7003d8e33921792f41771b7bd0177eff1821991eb000000006a473044022046b02669a46c0e9596af940a35bd8fb288f93a0ca70406e34be12b6b49176c5a0220544f55460a91c6c4e735e8b00a4c6d9dda08549af20bd00b70a0d5fef42eb6900121034e2ec662bbc43c046c3fc4bcb80a6c522715343a1728c126469710c377b7026bfffffffff115992fbecf126c38174f63180a4759e7e74b163ec0641d10ddcaaa566be9b4000000006b48304502210080e8a533c6603e11ccfac59fbd039151ce738b8e5cfe6d9afe250a33a632d1910220420f5e1f7ae8aa310cc98a533dd4d3a9e8867deb040c2aaf7438d118566d987c0121034e2ec662bbc43c046c3fc4bcb80a6c522715343a1728c126469710c377b7026bffffffff52dfc09a5795e7d2c0fa136706ba5c8fc18c35f60cf79bbcf1daf9710629313f000000006a47304402201b5481376b0166db7ecaa4511eea099aac7e4ebdf50b01b49259cf94853a6ea9022071db6c25a0564fafa92e7ad9fad0dd8c7714e6c3a3fdabedf2d721a6b7d997a50121034e2ec662bbc43c046c3fc4bcb80a6c522715343a1728c126469710c377b7026bffffffff860b58e8ab1c1181f7f8d430305fcf4d1c752f6a4dc486ff4dd77479ec670b03000000006b4830450221009f7f3111331570eef579606cbba9f1952a1a79ce32ee10959131125ec56f9a5602204ed3c016e043098a9eceb958847dfc2f8c91f1d5a2536279c7cfea403869e4af0121034e2ec662bbc43c046c3fc4bcb80a6c522715343a1728c126469710c377b7026bffffffff7c37558b93ba5ad7675c8a07d3040f66dfeb33170bddec1063bf3eece9faa7b2000000006b483045022100ee9c6b44e1b16dfc4dfe225c7e221d22fb4dd714eb0d4b1609443e7e1ffa854302203761122e5ed9e82b6d7389e5a8a752058bc1bdace56863b5c74a6876eecb74600121034e2ec662bbc43c046c3fc4bcb80a6c522715343a1728c126469710c377b7026bffffffff0210270000000000001976a9145955949e5acb12cba1cb7582c7b98eba6cdbf24b88acc1022400000000001976a9143a62afc6a58bf99ae74d7eab7baf324790829bf788ac00000000```

**Comment by kvbogdanov** [comment]
How did you solve this?
