### ISSUE TITLE
Wrong estimate fee

### ISSUE THREAD

**Issue by Akais24** [bitpay/insight-api#605]
As I try to use /insight-api/utils/estimatefee in my server, it always return the value of -1 regardless of the block number.

Why does it happen and how to fix it?

**Comment by thackerronak** [comment]
any updates for -1 value?

**Comment by thackerronak** [comment]
@Akais24 I'm still getting -1. Can you please share a solution?

**Comment by Akais24** [comment]
Sorry but I leave my project about insight-api for 3 months ago
and I couldn't remember did i solve this problem or not.

I'm sorry for I cannot giving a help about this.

**Comment by matiu** [comment]
Please see bitcoind documentation about this issue. -1 means it is not possible to estimate a fee for the desired target.
