### ISSUE TITLE
Enhance address balance calculation

### ISSUE THREAD

**Issue by matiu** [bitpay/insight-api#62]
Probably using a optimized leveldb schema.

Related to https://github.com/bitpay/insight-api/issues/10

The current schema does not scale well for address with ~10000+ transactions like 
1dice8EMZmqKvrGE4Qc9bUFf9PX3xaYDp	

This should be taken in account also:
https://github.com/bitpay/insight-api/issues/31

**Comment by braydonf** [comment]
I believe this is still an issue, however I think we can address with: https://github.com/bitpay/bitcore-node/issues/354
