### ISSUE TITLE
ERROR: Bad genesis block. Network mismatch between Insight and bitcoind? Insight is configured for:regtest

### ISSUE THREAD

**Issue by mdance** [bitpay/insight-api#64]
In an attempt to make sense of all this stuff, I have been running a bitcoin-qt regtest network in an ubuntu virtualbox.

I am trying to setup Insight (http://github.com/bitpay/insight) as a blockchain explorer to work with my regtest network.

I have gotten Insight to work on my host computer with the livenet, but when attempting to run it with my regtest network with:

INSIGHT_NETWORK=regtest BITCOIND_USER=rpcuser BITCOIND_PASS=rpcpassword npm start

I get the following error:

[historic_sync] ERROR: Bad genesis block. Network mismatch between Insight and bitcoind? Insight is configured for:regtest

In the insight directory, I have attempted to add my regtest network definition to node_modules/insight-bitcore-api/node_modules/bitcore/networks.js

exports.regtest = {
  name: 'regtest',
  addressVersion: 0x6f,
  magic: hex('0b110907'),
  genesisBlock: {
    height: 0,
    nonce: 2,
    version: 1,
    hash: hex('0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206'),
    prev_hash: buffertools.fill(new Buffer(32), 0),
    timestamp: 1296688602,
    merkle_root: hex('4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b'),
    bits: 207fffff,
  },
  genesisBlockTx: module.exports.livenet.genesisBlockTx,
  proofOfWorkLimit: module.exports.livenet.proofOfWorkLimit,
  checkpoints: [], // need to put checkput blocks here
  addressPubkey: 111,
  addressScript: 196,
  keySecret: 239,
};

Which I have tried adapting from the other network definitions, and from issuing the following commands on my regtest bitcoin-qt console:

getblockhash 0

0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206

getblock 0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206

{
"hash" : "0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206",
"confirmations" : 1440,
"size" : 285,
"height" : 0,
"version" : 1,
"merkleroot" : "4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b",
"tx" : [
"4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b"
],
"time" : 1296688602,
"nonce" : 2,
"bits" : "207fffff",
"difficulty" : 0.00000000,
"chainwork" : "0000000000000000000000000000000000000000000000000000000000000002",
"nextblockhash" : "0000581e0f63f734c0f6345c69e727d58a0bea7247c492326abe2b08a2d83820"
}

**Comment by ondrejsika** [comment]
do you have plan to add regtest to network conf? if not why?

**Comment by olalonde** [comment]
Possibly related: https://github.com/bitpay/bitcore/issues/1190

**Comment by posita** [comment]
> do you have plan to add regtest to network conf? if not why?

See also #103.

**Comment by braydonf** [comment]
bitcore-node supports running with regtest, and likewise should be fixed with v0.3.0. You can reference the `integration/regtest-node.js`: https://github.com/bitpay/bitcore-node/blob/master/integration/regtest-node.js
