### ISSUE TITLE
bitcore fail on npm update

### ISSUE THREAD

**Issue by Fcases** [bitpay/insight-api#72]
1863 verbose from cache /storage/insight-api/node_modules/bitcore/package.json
21864 info preuninstall bitcore@0.1.18
21865 info uninstall bitcore@0.1.18
21866 verbose true,/storage/insight-api/node_modules,/storage/insight-api/node_modules unbuild bitcore@0.1.18
21867 info postuninstall bitcore@0.1.18
21868 error Error: invalid version: 3001.0001.0000-dev-harmony-fb
21868 error     at validVersion (/usr/lib/nodejs/read-package-json/read-json.js:573:40)
21868 error     at final (/usr/lib/nodejs/read-package-json/read-json.js:323:23)
21868 error     at /usr/lib/nodejs/read-package-json/read-json.js:139:33
21868 error     at cb (/usr/lib/nodejs/slide/lib/async-map.js:48:11)
21868 error     at /usr/lib/nodejs/read-package-json/read-json.js:251:40
21868 error     at fs.js:268:14
21868 error     at /usr/lib/nodejs/graceful-fs/graceful-fs.js:103:5
21868 error     at Object.oncomplete (fs.js:107:15)
21869 error If you need help, you may report this log at:
21869 error     <http://bugs.debian.org/npm>
21869 error or use
21869 error     reportbug --attach /storage/insight-api/npm-debug.log npm
21870 error System Linux 3.11.0-20-generic
21871 error command "/usr/bin/nodejs" "/usr/bin/npm" "update"
21872 error cwd /storage/insight-api
21873 error node -v v0.10.15
21874 error npm -v 1.2.18
21875 verbose exit [ 1, true ]

**Comment by braydonf** [comment]
Outdated version, should no longer be an issue.
